### ISSUE TITLE
Multijira

### ISSUE THREAD

**Issue by LuisLorca** [shridhar-tl/jira-assistant#69] opened 2019-02-26 16:55 UTC
Would it be possible to use Jira Assistant in two different instances of Jira?

I work with two instances of Jira and it would be great to be able to manage both from Jira Assistant

**Comment by l2thmonkey** [comment] 2019-07-30 15:02
making this work with multiple instances would be amazing. I currently work with 7 different instances, even if i could only have a different dashboard for each that would be great, is this in the works?

**Comment by shridhar-tl** [comment] 2019-08-13 04:19
Hi @LuisLorca @l2thmonkey ,
In the new version of Jira Assistant (currently being developed), you can switch between multiple instance easily. It should be available in the mid of Sep 2019. But for now, you can logout from Jira Assistant and then Integrate with another Jira url. This way you can use multiple instance. You can switch back to your previous instance by doing the same again with old url.

**Comment by shridhar-tl** [comment] 2019-09-02 17:12
Hi @LuisLorca @l2thmonkey ,
New BETA version of Jira Assistant is published. Once it gets updated in your system, you should be able to switch to it and use it. New beta version contains the option requested by you. You can click on the user name in left hand side above menus and you will get options to integrate with new account or switch to different instance. More features are on the way! 

Please have a look at it and let me know if that helps you.

**Comment by LuisLorca** [comment] 2019-09-04 10:38
Hi @shridhar-tl:

Thanks for the feature.

I suppose that is because is yet BETA, but when you change between Instances JA doesn't refresh properly and show the configuration of the previous Instance. You have to force the refresh by F5.

FYI

**Comment by shridhar-tl** [comment] 2019-09-04 16:02
I understand what you say and I will have to check if their is a possibility for this issue to happen and will do it this weekend. But I also have a different doubt.

If I am correct, I believe you misunderstood the issue. When you click on different instance, that instance opens in different tab and your current page will remain the same using the old instance.

Currently for different instances, you will have to configure the settings separately. This restriction is due to the fact how Jira Assist is primarily developed.

For all instances to share the configuration first I will have to identify and split the settings page which can be shared with multiple instances. Definitely this restriction would be resolved in near future, but until old version of Jira Assistant is removed I will not be able to proceed with this as it would affect the old version.

Once this new version stabilizes then first I will split the settings and generalize it for all instance. Till then, unfortunately you will have to configure it in each instance you are using.

**Comment by LuisLorca** [comment] 2019-09-05 09:15
Hi @shridhar-tl:

When I click in the differents instances doesn't do anything, I have to refresh to change.

I send you a gif where you can see that it doen't work:

![jira](https://user-images.githubusercontent.com/48026584/64317063-e38a4d00-cfb6-11e9-9975-c24f7f9066cc.gif)

On the other hand, I understood that the lougout function "eliminate" your instance in JA. I tried and it open a new tab where you can put  the instance adrees, but if you open ja you have the same instances. I attach a gif.

![jiraLogOut](https://user-images.githubusercontent.com/48026584/64328689-34597000-cfce-11e9-8006-4f39edaaa08f.gif)


Thanks for all!

**Comment by shridhar-tl** [comment] 2019-09-06 02:49
@LuisLorca - Thank you for taking time to reproduce the issue with an image. This issue has been resolved now and will be published this weekend. You can verify it next week.

**Comment by shridhar-tl** [comment] 2019-09-30 03:01
Hi @LuisLorca @l2thmonkey - Is the functionality you are expecting working fine in new BETA version? Can you please confirm it?

**Comment by LuisLorca** [comment] 2019-09-30 08:45
Hi @shridhar-tl!!!

It works fine. But it would be great if in the instances you could give it a name and that it could be seen to differentiate in which one you are.

Thanks for all

**Comment by shridhar-tl** [comment] 2019-10-05 11:44
Hi @LuisLorca - I hope you would have seen your request implemented in latest version. Currently it looks clumsy, but I hope soon after the Switch back button is removed from header it should look better  . Closing this issue assuming all the requests are fulfilled at the moment. You can reopen this issue if you still face any issue.

**Closed by shridhar-tl** 2019-10-05 11:44 UTC
Labels: bug, in live testing
