### ISSUE TITLE
Text not readable in Dark theme

### ISSUE THREAD

**Issue by irahhari** [shridhar-tl/jira-assistant#335] opened 2023-10-15 14:28 UTC
### Checklist before you being

- [X] I am sure that I am already using latest version of Jira Assistant
- [X] I had verified that, no similar issues are already reported in [issue tracker](https://github.com/shridhar-tl/jira-assistant/issues)
- [X] I had tried reproducing this issue with with [Web version of Jira Assistant](https://app.jiraassistant.com) to ensure that this issue is not recently fixed and yet to be published
- [X] I had verified that, my query is not answered in [FAQ section of website](https://www.jiraassistant.com/faq)
- [X] I had verified that, my issue is not listed as [known bugs in website](https://www.jiraassistant.com/version-history)

### How do you use Jira Assistant?

Browser extension

### Are you using cloud version of Jira or self hosted (data center / server) of Jira.

Self hosted (datacenter)

### Version of Jira Assistant

2.56, Web

### What browser are you using?

Chrome

### What OS are you using? You need not disclose this if you feel it is irr-relevant for your issue.

Not Disclosed

### Bug Description

The text in the announcement and notification is not readable in dark theme.

![image](https://github.com/shridhar-tl/jira-assistant/assets/76170080/81120cfc-7ef2-45fa-a79a-b367b035fcae)

This issue is similar to https://github.com/shridhar-tl/jira-assistant/issues/276

### Checklist before you submit

- [X] I have ensured not to paste any confidential information like Jira url, Mail id, etc.
- [X] I have verified my browser console logs and added necessary details (if required)
- [X] I have added required screenshots if the bug is related to UI (as necessary)

**Comment by shridhar-tl** [comment] 2023-10-16 03:49
Hi @irahhari
Thank you for reporting this issue. This issue has been resolved and would be available for extension users as part of upcoming release. However, this fix would be available for web users in next few mins once automated deployment process gets completed.

Closing this ticket considering the issue is resolved. Please feel free to reopen it if you see any additional issues.

**Closed by shridhar-tl** 2023-10-16 03:49 UTC
Labels: bug
