### ISSUE TITLE
Import Issues not working properly

### ISSUE THREAD

**Issue by stefanouazx** [shridhar-tl/jira-assistant#152] opened 2020-05-07 06:33 UTC
Hello, 
I uploaded a csv with a green light to procceed, but when i press the import button nothing is happening and a blank screen comes up.

**Comment by shridhar-tl** [comment] 2020-05-07 08:17
I was not able to reproduce any issues with my instance. Their is a possibility that bulk importing is disabled in your Jira. In that case I will provide an alternate option. Can you check the console and provide the error details? Also if possible you can just replace any confidential information in csv and share that as well so that I can try that from my end.

Please provide your browser details and JA version number as well

**Comment by stefanouazx** [comment] 2020-05-08 06:12
Bulk import is enable.
![Capture](https://user-images.githubusercontent.com/64948313/81375977-4403f800-910b-11ea-8f1e-5275c4d63379.JPG)
JA version 1.4 but my JIRA is version 8.8.0. Does this extension work on 8.8.0?
Chrome Version 81.0.4044.138 (Official Build) (32-bit)
Find attached the csv.
![image](https://user-images.githubusercontent.com/64948313/81376363-15d2e800-910c-11ea-9389-1d93c1dcc9ca.png)

**Comment by stefanouazx** [comment] 2020-05-08 06:17
[momjbjbjpbcbnepbgkkiaofkgimihbii-1588918642206.log](https://github.com/shridhar-tl/jira-assistant/files/4597294/momjbjbjpbcbnepbgkkiaofkgimihbii-1588918642206.log)
Console's error details

**Comment by shridhar-tl** [comment] 2022-07-14 05:53
This would be resolved or tracked as part of #219. Hence closing this issue.

**Closed by shridhar-tl** 2022-07-14 05:53 UTC
Labels: bug
