### ISSUE TITLE
create new issues based on templates

### ISSUE THREAD

**Issue by mrs-mrl** [shridhar-tl/jira-assistant#40] opened 2018-07-03 16:29 UTC
It would be great to have the ability to create issues from Jira Assistant based on pre-defined (by the user) issue templates.

The UI would look something like the bookmark gadget, but instead of bookmarked issues it'd display templates. The templates would include things like default summary, components, etc.

Choosing a template would either directly add a new issue, open a jira assistant internal UI to fill in the blanks or redirect you to the issue create page with your template data pre-entered. (whichever is easier)

I think a lot of this could already be achieved by implementing a smarter and more streamlined clone feature: right click on a bookmarked issue, select clone and be redirected to the issue create page with issue summary, description etc. already filled in with data from the 'template issue'. (This differs from atlassians implementation by having the ability to edit issue fields before cloning)[1]

I know there are commercial add-ons for jira that implement similar features, but these aren't really an option if you aren't the jira admin (or don't have the money).

[1] similar features are available with clone plus https://marketplace.atlassian.com/apps/44043/clone-plus-for-jira?hosting=server&tab=overview

**Comment by shridhar-tl** [comment] 2019-10-02 09:49
Hi @mrs-mrl , A new feature for bulk import of issues is now available. Hope this would solve the purpose. Still some enhancements are planned in that based on popularity.

**Comment by mrs-mrl** [comment] 2019-10-14 15:42
Thanks for the feedback and the work on this great add-on. I haven't been able to test the new version since I'm on Firefox, but I will try to at some point. From your description it doesn't sound like it, as the intention here was more to suggest a template feature that jira lacks and add-ons also half-heartedly implement.

Do you plan on supporting Firefox at some point in the future?

**Comment by shridhar-tl** [comment] 2019-10-15 04:31
Hi @mrs-mrl , Yes, once the new beta version becomes stable, I will have it published to Firefox and going forward both Chrome and Firefox will keep getting all the updates. Until new version becomes stable I cannot publish it to Firefox as I cannot have both the new versions and old version to gather in Firefox due to some restrictions with store. You can expect it to be available for Firefox by another 2 weeks approximately.

**Comment by xabdmvx** [comment] 2020-03-12 01:30
> Hi @mrs-mrl , A new feature for bulk import of issues is now available. Hope this would solve the purpose. Still some enhancements are planned in that based on popularity.

Hi, today I were testing the bulk import feature, but I got a problem,
I am having issue to import values to user fields.
it works when I use my jira user id, but then the problem is that Jira stop supporting user ids since 2018, 

> [Say goodbye to usernames in Atlassian Cloud](https://confluence.atlassian.com/cloud/blog/2018/06/say-goodbye-to-usernames-in-atlassian-cloud?_ga=2.161578552.565566597.1583950383-2009462997.1576619607)

my jira user id is old, so it works in the import feature, but I dont know what value to use to be able to import other users in Jira that does not have user id more than their email. I already tried with the login email but it does not work. 

Let me know what value can I use instead of the Jira user name.

Thanks

**Comment by shridhar-tl** [comment] 2020-03-16 06:19
@xabdmvx - I expect the email to work for this case. But if it is not working I will check and resolve it ASAP (max by this weekend).

**Comment by shridhar-tl** [comment] 2020-03-17 15:50
@xabdmvx - The issue you reported about email not accepted in user field is now resolved and will be published soon. It will be available once your version gets updated to v0.98.

**Comment by shridhar-tl** [comment] 2022-12-27 15:42
I hope this implementation is done and hence closing this issue. If there are any more issues, a separate ticket can be raised.

**Closed by shridhar-tl** 2022-12-27 15:42 UTC
Labels: enhancement
