### ISSUE TITLE
Open Tickets JQL not editable.

### ISSUE THREAD

**Issue by masteryoda121** [shridhar-tl/jira-assistant#325] opened 2023-09-07 16:34 UTC
### Checklist before you being

- [X] I am sure that I am already using latest version of Jira Assistant
- [X] I had verified that there are no existing requests with similar suggestion in [issue tracker](https://github.com/shridhar-tl/jira-assistant/issues)
- [X] I had verified that, my query is not answered in [FAQ section of website](https://www.jiraassistant.com/faq)

### How do you use Jira Assistant?

Browser extension

### Are you using cloud version of Jira or self hosted (data center / server) of Jira.

Cloud Jira

### Version of Jira Assistant

2.55

### What browser are you using?

Firefox

### Feature Suggestion

The Open Tickets JQL is not editable.
This makes the feature worthless when needing to modify the JQL.

Example: Johnny is working for the A-Team in XYZ company.
He get transferred to the B-Team.
His A-Team Jira stories have not been reassigned to other A-Team developers.
So, now he see both his A-Team and B-Team Jira assignments.
He only want to see his B-Team assignments.

![JQL](https://github.com/shridhar-tl/jira-assistant/assets/144371160/8a5da24b-8f7b-4cff-a9f6-03695fe97152)

### Checklist before you submit

- [X] I have ensured not to paste any confidential information like Jira url, Mail id, etc.
- [X] I have added required screenshots (as necessary)

**Comment by shridhar-tl** [comment] 2023-09-15 01:38
Hi @masteryoda121 ,
This is duplicate of #158 #246 and #324. You will get your answer in that ticket.

Additionally, a search with keywords in official website may some times provide you with quick answer. Following search results include a FAQ which answers this question as well:

https://jiraassistant.com/search/open%20tickets%20jql%20not%20editable/

Closing this ticket assuming your issue is resolved. Please feel free to get back to me for any other queries.

**Closed by shridhar-tl** 2023-09-15 01:38 UTC
