### ISSUE TITLE
Worklog Report New is missing items which are shown on Worklog Report Old

### ISSUE THREAD

**Issue by peterwatersfis** [shridhar-tl/jira-assistant#254] opened 2023-01-05 15:53 UTC
### Checklist before you being

- [X] I am sure that I am already using latest version of Jira Assistant
- [X] I had verified that, no similar issues are already reported in [issue tracker](https://github.com/shridhar-tl/jira-assistant/issues)
- [X] I had tried reproducing this issue with with [Web version of Jira Assistant](https://app.jiraassistant.com) to ensure that this issue is not recently fixed and yet to be published
- [X] I had verified that, my query is not answered in [FAQ section of website](https://www.jiraassistant.com/faq)
- [X] I had verified that, my issue is not listed as [known bugs in website](https://www.jiraassistant.com/version-history)

### How do you use Jira Assistant?

Browser extension

### Are you using cloud version of Jira or self hosted (data center / server) of Jira.

Self hosted (datacenter)

### Version of Jira Assistant

v2.44

### What browser are you using?

Edge

### What OS are you using? You need not disclose this if you feel it is irr-relevant for your issue.

Windows

### Bug Description

Running the New Worklog Report for a group of users and a date range returns different results to Old Worklog report:
![image](https://user-images.githubusercontent.com/54357815/210822908-65e3987c-a152-4a9d-8da5-f9e7c810dbc3.png)
![image](https://user-images.githubusercontent.com/54357815/210822955-aa9b4353-1384-417c-84d5-4ffc080d3d4c.png)
![image](https://user-images.githubusercontent.com/54357815/210823039-f53e114d-42c7-462a-909e-9e0057462384.png)
![image](https://user-images.githubusercontent.com/54357815/210823104-2fa4799d-5035-44ed-bb12-0a474e8ed970.png)
![image](https://user-images.githubusercontent.com/54357815/210823174-ffd5a071-e0ae-4d79-add3-8943e30551f7.png)

### Checklist before you submit

- [X] I have ensured not to paste any confidential information like Jira url, Mail id, etc.
- [X] I have verified my browser console logs and added necessary details (if required)
- [X] I have added required screenshots if the bug is related to UI (as necessary)

**Comment by shridhar-tl** [comment] 2023-01-05 16:02
Hi @peterwatersfis, Thank you for reporting this issue. There is already a similar issue reported #253. I will look into this issue and try to resolve it ASAP.

But for now, please let me know if the users you are viewing report for is from same timezone as yours or different timezone? Because there is a timezone configuration which could be different in both the reports. Please have a look at it once and I will try to reproduce this issue from my end.

**Comment by peterwatersfis** [comment] 2023-01-05 16:07
Hi, the two users which are missing data on the New Worklog report are in the same timezone, and other users which are correctly reporting are also in this same timezone, thanks, Peter

**Comment by shridhar-tl** [comment] 2023-01-05 17:22
Also can you verify if the user for whom worklog is not pulled in new report have logged on some issues which is having lots of worklogs, say like more than 5000 worklogs in a single issue?

**Comment by shridhar-tl** [comment] 2023-01-06 05:23
Hi @peterwatersfis, I have tried alot by adding 1000's of worklog on various combinations and I couldn't reproduce the issue which you have reported. Hence I would require your help in understanding the issue:

1) Please check with web version once and see if you were able to reproduce the issue.
2) By any change see if you have configured Log filter or JQL filter in new worklog report.  Refer to this comment for a screenshot: https://github.com/shridhar-tl/jira-assistant/issues/253#issuecomment-1372397935
3) In old and new worklog report expand the user for whom you see the difference and try to find which issue is having this discrepancy and see if that issue is returned by Jira in network tab for new report. Also see if there are lots of worklogs (more than 5000) for that issue.
4) Sometimes if Jira is not reindexed recently, then it randomly miss some worklog. This issue was resolved in Jira Cloud, but I haven't heard that it is resolved in Datacenter version. So you can check when was the last time Jira was reindexed.

As of now I am out of ideas on what else to try. But I will think through it while you try these options and get back to me.

**Comment by peterwatersfis** [comment] 2023-01-06 09:13
Hi, I have tried to New Worklog report for the individual user and this is the result:
![image](https://user-images.githubusercontent.com/54357815/210968264-24b78c11-c621-4e2a-b24e-6892335988f1.png)
Comparing this to the Old Worklog report for the same user:
![image](https://user-images.githubusercontent.com/54357815/210968377-8cd9dc31-a5bb-4b60-a976-038cbc312910.png)

I am running the Web version.

This is the Log Filter for the New Report:
![image](https://user-images.githubusercontent.com/54357815/210968646-55761de4-80ae-4f95-9246-5c864f4b4311.png)
The New and Old Reports have this in Jira Filter:
![image](https://user-images.githubusercontent.com/54357815/210968755-fbec63e5-82e4-46cd-9c84-91bb8c03c54b.png)
This is the Report Configuration for the Old report:
![image](https://user-images.githubusercontent.com/54357815/210968945-3296049d-5511-421c-9592-0c8063ac67cd.png)
this is the Report Configuration for the New report:
![image](https://user-images.githubusercontent.com/54357815/210969026-81d3b9cd-48b9-4743-8fa3-96b80606ffd0.png)
There are not more than 5,000 report items for the user, these are the Old Report items:
![image](https://user-images.githubusercontent.com/54357815/210969208-763d5d6f-4889-4040-96da-79c76b66ab3f.png)
There are no New report items for this user:
![image](https://user-images.githubusercontent.com/54357815/210969306-ecf2441f-a432-4527-983d-b2561ec053d1.png)

I will ask our admin team when our Jira was last indexed.
Thanks.

**Comment by peterwatersfis** [comment] 2023-01-06 09:58
Interesting observation is that when both New and Old Worklog reports are run and the Flat (Groupable) tab is selected, the same number of rows are returned and the data for both reports is identical.

**Comment by shridhar-tl** [comment] 2023-01-06 15:37
Hi @peterwatersfis - Thank you providing the details. 

However regarding the 5000 worklog items I did not mention in report. I asked if there are more than 5000 worklog items in Jira itself. You can check the network tab and while request goes to server for that ticket you can see max results and total results field. If that is more than 5000 then sometimes we have observed Jira randomly does not return data for certain request. Once again, most of the times such behaviors' use to be due to indexing issues only.

Next thing, if you are available for a screenshare session either tomorrow or on Sunday, you can send me an invite and I can join at that time. I would be able to join zoom call any time between 9AM IST to 10PM IST if you could send invite couple of hours in advance.

I'm usually not available for calls, but this being very critical issue and not being able to reproduce even after hours of effort from my end, would like to debug it over screenshare session if it is possible for you. Around 30 mins should do.

**Comment by peterwatersfis** [comment] 2023-01-06 16:14
Hi, @shridhar-tl , we will have more that 5,000 worklog items. I do not work over the weekend so could not do a call tomorrow or Sunday, but can do a weekday.
While I wait for out Jira admin team to respond to my index question I am using the Grouped Tab view of the Old Worklog data which is correct.
Peter

**Comment by shridhar-tl** [comment] 2023-01-25 02:12
Hi @peterwatersfis - JA v2.47 is already published and do you still see this issue with latest version of JA? I was not able to reproduce this exact issue with any kind of data, However there are multiple fixes around this use case. Hence its worth a try again.

**Comment by shridhar-tl** [comment] 2023-02-19 14:57
I am finding it very hard to reproduce this issue. If anyone else is facing this issue, please contact me and I would like to know if you were able to provide some clue to identify the root cause. You can either provide the details here or contact me via email.

**Comment by shridhar-tl** [comment] 2023-02-25 03:32
Hi @peterwatersfis - Any updates on my comments above? Did the issue resolve for you?

**Comment by shridhar-tl** [comment] 2023-03-06 04:32
Hi @peterwatersfis - I consider this issue is resolved and is available in JA v2.48. It is already available for Chrome and Firefox users. For edge it would soon be published. You can either upgrade to latest version or test it with web version.

However I'm closing this issue considering it is resolved. If you still face any issue, please feel free to reopen it.

**Closed by shridhar-tl** 2023-03-06 04:32 UTC
Labels: bug, duplicate, awaiting input
