### ISSUE TITLE
Import User Groups 

### ISSUE THREAD

**Issue by andrei0581** [shridhar-tl/jira-assistant#308] opened 2023-07-06 11:48 UTC
### Checklist before you being

- [X] I am sure that I am already using latest version of Jira Assistant
- [X] I had verified that, no similar issues are already reported in [issue tracker](https://github.com/shridhar-tl/jira-assistant/issues)
- [X] I had tried reproducing this issue with with [Web version of Jira Assistant](https://app.jiraassistant.com) to ensure that this issue is not recently fixed and yet to be published
- [X] I had verified that, my query is not answered in [FAQ section of website](https://www.jiraassistant.com/faq)
- [X] I had verified that, my issue is not listed as [known bugs in website](https://www.jiraassistant.com/version-history)

### How do you use Jira Assistant?

Browser extension

### Are you using cloud version of Jira or self hosted (data center / server) of Jira.

Self hosted (datacenter)

### Version of Jira Assistant

v2.51

### What browser are you using?

Chrome

### What OS are you using? You need not disclose this if you feel it is irr-relevant for your issue.

Windows

### Bug Description

When trying to import and user group defined , i get only the Group Names and the first member in each group.
In the exported jab file i can find all the group members .

### Checklist before you submit

- [X] I have ensured not to paste any confidential information like Jira url, Mail id, etc.
- [X] I have verified my browser console logs and added necessary details (if required)
- [X] I have added required screenshots if the bug is related to UI (as necessary)

**Comment by shridhar-tl** [comment] 2023-07-20 03:40
hi @andrei0581, Thank you for reporting this issue. But I was not able to reproduce this case in my end for Jira Cloud version. However, I reviewed the code and identified account id is used while importing the user which would not work for Data center edition of Jira like in your case.

So now the fix is available in Web version of JA. You can use web version of JA for now just by visiting https://app.jiraassistant.com.

I would push the changes to extension users by this week end and you should be able to see the fixes after your extension gets updated to JA v2.51.

Closing this ticket assuming your issue is resolved. Please feel free to reopen this ticket if you still face any issue.

**Closed by shridhar-tl** 2023-07-20 03:40 UTC
Labels: bug, in live testing
