### ISSUE TITLE
Unable to integrate to Jira Assistant

### ISSUE THREAD

**Issue by manasa08april** [shridhar-tl/jira-assistant#129] opened 2020-02-20 09:41 UTC
I am unable to integrate to jira assistant. It always shows me network server error.
PLease check
"This is not a valid Jira server url or the server does not respond."
Where as we are using the same jira url

**Comment by Szabotic** [comment] 2020-02-20 09:42
I think the URL is meant to be:

https://abrac.atlassian.net

Try that and it should work

**Comment by manasa08april** [comment] 2020-02-20 10:00
[image: image.png]

getting the above error on trying with the suggested url.

**Comment by manasa08april** [comment] 2020-02-20 10:00
![image](https://user-images.githubusercontent.com/60995998/74922918-f0301f80-53f5-11ea-832f-0d76d237923f.png)
GEtting the above error

**Comment by vinaychavadi** [comment] 2020-02-20 10:38
> I am unable to integrate to jira assistant. It always shows me network server error.
> PLease check
> "This is not a valid Jira server url or the server does not respond."
> Where as we are using the same jira url
> ![image](https://user-images.githubusercontent.com/60995998/74921054-2fa93c80-53f3-11ea-97c7-5c5ee95b34e3.png)

Same issue

**Comment by manasa08april** [comment] 2020-02-20 10:46
> I think the URL is meant to be:
> 
> https://abrac.atlassian.net
> 
> Try that and it should work

**Comment by belek** [comment] 2020-02-20 10:51
It works on Firefox, Jira Assistant 0.96

**Comment by shridhar-tl** [comment] 2020-02-20 11:05
Please try using Firefox version for now. v0.96 would be available in chrome in next 4-5 days depending on the review process in chrome web store. At the mean time try to open console and check if you see any errors related to CORS. If you see it then their is no immediate solution as this is due to an update in chrome browser and I am yet to figure out a way to solve it.

**Comment by vinaychavadi** [comment] 2020-02-20 11:14
New Version on Firefox seems to work.. little slow but works.. Thanks a lot  Shridhar!!

**Comment by shridhar-tl** [comment] 2020-02-20 11:33
Hi @vinaychavadi - I know it it bit slow. Due to the security updates given by Chrome currently (which will be published for Firefox also later), I will have to change some approach to have the tool overcome those restrictions which made requests to Jira bit slower. I will try and find a better option once the tool becomes stable once again.

**Comment by vinaychavadi** [comment] 2020-02-20 13:45
Thanks Shridhar. This tool is of great help for all of us who log our work in Jira in our organization. Thanks for your help. We look forward the new version of the tool. For now this is works :)

**Comment by mahimabhowmik** [comment] 2020-02-21 01:00
> Hi @vinaychavadi - I know it it bit slow. Due to the security updates given by Chrome currently (which will be published for Firefox also later), I will have to change some approach to have the tool overcome those restrictions which made requests to Jira bit slower. I will try and find a better option once the tool becomes stable once again.

I am still getting the same error as mentioned in the thread in both Chrome and Firefox.

**Comment by vinaychavadi** [comment] 2020-02-21 08:23
The new 0.96 version is available now on Chrome and seems to be working fine.

**Comment by Sixcross** [comment] 2020-02-21 08:50
When selecting a Date on "Worklog Report" i still get the "One or more Actions Failed".
All the other reports seem to work fine.

Version: 0.96
Browser: Firefox and Chrome

**Comment by manasa08april** [comment] 2020-02-21 09:58
I am getting the same error as mentioned above

**Comment by kusd24** [comment] 2020-02-21 11:01
Please fix the error opening the Worklog Report. The error occurs since version 0.94 and higher

![image](https://user-images.githubusercontent.com/61314664/75029175-2b088500-54d4-11ea-8a98-7648a0c0438b.png)

**Comment by emaillenin** [comment] 2020-02-23 09:57
> Please try using Firefox version for now. v0.96 would be available in chrome in next 4-5 days depending on the review process in chrome web store. At the mean time try to open console and check if you see any errors related to CORS. If you see it then their is no immediate solution as this is due to an update in chrome browser and I am yet to figure out a way to solve it.

@shridhar-tl 
Getting the following error when installing JiraAssist_Latest.xpi in Firefox 73.0.1

![image](https://user-images.githubusercontent.com/1235853/75110172-0f8dad80-567f-11ea-9168-f0e5223ef49a.png)

**Comment by emaillenin** [comment] 2020-02-23 10:09
I have got it working by installing Firefox Developer edition and diabled `xpinstall.signatures.required`, `xpinstall.whitelist.required` and `extensions.langpacks.signatures.required` and then installing from the XPI file.

**Comment by shridhar-tl** [comment] 2020-02-28 17:49
Duplicate of #126 . Hence closing this issue. You can track for any updates through #126. Also v0.97 is already available in Firefox and should fix all the issues mentioned. For chrome it would take some time for the review to be completed by Google and hence expected date for the update to be available for chrome users is 3rd of March 2020.

**Closed by shridhar-tl** 2020-02-28 17:49 UTC
