### ISSUE TITLE
Worklog load error on dashboard and reports

### ISSUE THREAD

**Issue by tagplus5** [shridhar-tl/jira-assistant#198] opened 2021-10-05 09:52 UTC
There is an error on dashboard or or worklog report:
```
TypeError: Cannot read properties of undefined (reading 'indexOf')
    at ie.isHoliday (index.eb12c961.chunk.js:1)
    at 18.d735d168.chunk.js:1
    at Array.map (<anonymous>)
    at ne.getDayWiseReportData (18.d735d168.chunk.js:1)
    at ne.refreshData (18.d735d168.chunk.js:1)
    at fo (4.44d8a5ec.chunk.js:2)
    at as (4.44d8a5ec.chunk.js:2)
    at hu (4.44d8a5ec.chunk.js:2)
    at t.unstable_runWithPriority (4.44d8a5ec.chunk.js:2)
    at zi (4.44d8a5ec.chunk.js:2)
```
![image](https://user-images.githubusercontent.com/2699260/136000601-7f5e6f80-314e-41bf-a1ba-7e7f4f90d3d5.png)

**Comment by shridhar-tl** [comment] 2021-10-05 14:13
Duplicate of #196 . Check the mentioned issue for workaround / solution.

**Closed by shridhar-tl** 2021-10-05 14:13 UTC
