### ISSUE TITLE
Unable to integrate with outlook due to redirect URI error

### ISSUE THREAD

**Issue by shhs125** [shridhar-tl/jira-assistant#328] opened 2023-09-22 15:46 UTC
### Checklist before you being

- [X] I am sure that I am already using latest version of Jira Assistant
- [X] I had verified that, no similar issues are already reported in [issue tracker](https://github.com/shridhar-tl/jira-assistant/issues)
- [X] I had tried reproducing this issue with with [Web version of Jira Assistant](https://app.jiraassistant.com) to ensure that this issue is not recently fixed and yet to be published
- [X] I had verified that, my query is not answered in [FAQ section of website](https://www.jiraassistant.com/faq)
- [X] I had verified that, my issue is not listed as [known bugs in website](https://www.jiraassistant.com/version-history)

### How do you use Jira Assistant?

Browser extension

### Are you using cloud version of Jira or self hosted (data center / server) of Jira.

Not sure

### Version of Jira Assistant

v2.55

### What browser are you using?

Chrome

### What OS are you using? You need not disclose this if you feel it is irr-relevant for your issue.

Windows

### Bug Description

When I try to integrate my outlook at work, I get the following ERROR message and I am unable to integrate with outlook. Not sure what the redirect URI is supposed to be. Any help appreciated,

Sorry, but we’re having trouble signing you in.
AADSTS50011: The redirect URI 'https://www.jiraassistant.com/oauth/outlook' specified in the request does not match the redirect URIs configured for the application 'a8efd8fc-0657-490e-a622-7b2aaa4f4f46'. Make sure the redirect URI sent in the request matches one added to your application in the Azure portal. Navigate to https://aka.ms/redirectUriMismatchError to learn more about how to fix this.

Troubleshooting details
If you contact your administrator, send this info to them.
[Copy info to clipboard](https://login.microsoftonline.com/kmsi#)
Request Id: 2a07526c-bf65-4106-b78c-5f8772423400
Correlation Id: 0c88afd1-b88f-4571-bdc6-9f60ee7a0e46
Timestamp: 2023-09-22T15:35:31Z
Message: AADSTS50011: The redirect URI 'https://www.jiraassistant.com/oauth/outlook' specified in the request does not match the redirect URIs configured for the application 'a8efd8fc-0657-490e-a622-7b2aaa4f4f46'. Make sure the redirect URI sent in the request matches one added to your application in the Azure portal. Navigate to https://aka.ms/redirectUriMismatchError to learn more about how to fix this.

### Checklist before you submit

- [X] I have ensured not to paste any confidential information like Jira url, Mail id, etc.
- [X] I have verified my browser console logs and added necessary details (if required)
- [X] I have added required screenshots if the bug is related to UI (as necessary)

**Comment by shridhar-tl** [comment] 2023-09-22 16:46
Duplicate of #327. This issue has already been resolved in Jira Assist v2.56. Please update your extension and you should see it working.

 If you want to update to latest version of extension, you can do so by going to "chrome://extension", enable dev mode from top right corner and then click on update button from top left corner. That would get your extension updated to latest available version and you should see the issue resolved.

Closing this ticket considering your issue is resolved. Please feel free to reopen this ticket or create new ticket if you face some other issues.

**Closed by shridhar-tl** 2023-09-22 16:46 UTC
Labels: bug, duplicate
