### ISSUE TITLE
Unable to fetch the data of issue work log in jira assistant plugin day wise for one particular issue.

### ISSUE THREAD

**Issue by Saicharan-idexcel** [shridhar-tl/jira-assistant#244] opened 2022-11-17 07:56 UTC
Unable to fetch the data of issue work log in jira assistant plugin day wise for one particular issue.

**Comment by shridhar-tl** [comment] 2022-11-24 03:53
@Saicharan-idexcel - Please look at the suggestion provided in #242. Though issue looks different, I believe the root cause is same. Please try the same solution and let me know if it solves your issue.

**Comment by gzarinac** [comment] 2022-11-25 08:59
@Saicharan-idexcel, I have the same issue with the Jira cloud but _"The most recent version of JIRA Cloud is no longer using the traditional indexing method, and as such, the option to trigger a re-index has been removed._"
Any suggestions?

**Comment by NateFort** [comment] 2022-11-27 17:58
@Saicharan-idexcel reindexing is no longer an option. I also get the following when trying to do a Worklog Report 
![image](https://user-images.githubusercontent.com/22970753/204151916-488f748d-b56e-4e23-8831-d84c94074d66.png)

**Comment by shridhar-tl** [comment] 2022-11-30 04:04
Hi, I did not realize you are using Cloud version of JIRA. Of course if I had known you are using cloud, I wouldn't have suggested this option.

So far no one else has reported such issue with cloud version. So I do not have any clue at this point. Thank you for including the console log. But for this use case network log could be more useful. Will you be able to send the screenshot of network log particularly with response code and if possible response data partially visible.

Please ensure you do not expose any sensitive information in screenshot as this is a public forum.

**Comment by shridhar-tl** [comment] 2022-12-12 03:29
I heard from a different user in #242 that they have too many worklogs in that issue and that is the reason they were not able to pull it. See if you have something related to that. Not just Worklogs, look at comments and change history as well. if there are 1000's of entry, then that could be one of the possible cause.

**Comment by gzarinac** [comment] 2022-12-15 11:07
A colleague of mine said that Atlassian recently implemented paging on Jira API and that you should implement it to enable the correct fetching of worklog calendar data. I hope this will help.

**Comment by shridhar-tl** [comment] 2022-12-15 16:57
Hi @gzarinac, paging was there since too many years and already tool is capable of pulling data from multiple pages for both issues and for worklog. How ever let me check if there is something changing in API anyway and get back on this by this weekend.

**Comment by gzarinac** [comment] 2022-12-16 08:32
@shridhar-tl great, thnx. If you need any additional information or I can help somehow, please let me know.

**Comment by shridhar-tl** [comment] 2022-12-18 11:55
Hi @gzarinac , you are right. Pagination was missing in worklog report implementation. Though I know worklog reports were paged, I somehow did not have the implementation for worklogs. I still haven't added pagination, but had added additional filters so that worklog count should get reduced based on latest options available in worklog api.

This fix is only available in Web as of now. You can try it from web version and let me know if this issue has been resolved: https://app.jiraassistant.com

**Comment by gzarinac** [comment] 2022-12-19 07:33
Hi @shridhar-tl, I try from the web version, and my worklog is empty, with no entries at all.

**Comment by shridhar-tl** [comment] 2022-12-20 08:14
Hi @gzarinac, the usual question, do you see any console errors now? and currently where are you checking? from calendar or from worklog report or from dashboard gadget?

**Comment by gzarinac** [comment] 2022-12-20 13:07
Hi @shridhar-tl,
I use Worklog Calendar from the browser extension, and it shows partial data.
I tried from Jira Assistant Web a few minutes ago, and It works now.
I can see all my calendar entries again.

**Comment by shridhar-tl** [comment] 2022-12-20 13:18
@NateFort  and @Saicharan-idexcel - Hoping your issue is also resolved. Please let me know if you are still facing any issues.

**Comment by shridhar-tl** [comment] 2022-12-27 15:53
This implementation is done and hence closing this issue. This change is already available in Web version and you would start seeing the changes in Extension and Cloud App once you are updated to JA v2.44.

**Closed by shridhar-tl** 2022-12-27 15:53 UTC
Labels: bug, in live testing
