### ISSUE TITLE
Unable to add worklog on Custom Report

### ISSUE THREAD

**Issue by smi60** [shridhar-tl/jira-assistant#322] opened 2023-08-30 08:26 UTC
### Checklist before you being

- [X] I am sure that I am already using latest version of Jira Assistant
- [X] I had verified that, no similar issues are already reported in [issue tracker](https://github.com/shridhar-tl/jira-assistant/issues)
- [X] I had tried reproducing this issue with with [Web version of Jira Assistant](https://app.jiraassistant.com) to ensure that this issue is not recently fixed and yet to be published
- [X] I had verified that, my query is not answered in [FAQ section of website](https://www.jiraassistant.com/faq)
- [X] I had verified that, my issue is not listed as [known bugs in website](https://www.jiraassistant.com/version-history)

### How do you use Jira Assistant?

Browser extension

### Are you using cloud version of Jira or self hosted (data center / server) of Jira.

Self hosted (datacenter)

### Version of Jira Assistant

v2.55

### What browser are you using?

Edge

### What OS are you using? You need not disclose this if you feel it is irr-relevant for your issue.

Windows

### Bug Description

I've created Custom report and add it to my dashboard.
When I try to add worklog on this report the "kebab" icon offers me option to add worklog, however no pop-up window opens.

I can Add issue to bookmarks or start timer, but Add worklog option does not work.

Additionally: right mouse click on the issue does not open menu, only the kebab icon does.

![image](https://github.com/shridhar-tl/jira-assistant/assets/143519212/b7b27a6c-c306-492f-bf11-a50d75ac2306)

### Checklist before you submit

- [X] I have ensured not to paste any confidential information like Jira url, Mail id, etc.
- [X] I have verified my browser console logs and added necessary details (if required)
- [X] I have added required screenshots if the bug is related to UI (as necessary)

**Comment by shridhar-tl** [comment] 2023-08-30 16:13
Thank you @smi60 for reporting this issue, however it is a known issue and is duplicate of #239. This is not prioritized so far as it is used by very limited number of users.

Will try to prioritize this issue ASAP, however as there is already an existing ticket, closing this ticket marking it as duplicate.

**Closed by shridhar-tl** 2023-08-30 16:13 UTC
Labels: bug, duplicate
