### ISSUE TITLE
Cannot see worklogs on calendar

### ISSUE THREAD

**Issue by sajjan-halarnkar** [shridhar-tl/jira-assistant#132] opened 2020-02-24 13:33 UTC
Hi,

From last week I have been not able to see my work log entries previously logged. I am able to enter new entries but they gets disappeared from the calendar once the calendar is refreshed. But I confirmed that the work logs are getting saved to Jira, only that they have now stopped showing in the calendar.

When I open the calendar, I get the below error :
![image](https://user-images.githubusercontent.com/61407519/75156205-9c943d80-5737-11ea-82d4-e0dd728a2035.png)

Not sure if the issue is due to above error. Can you please suggest a solution to this?

Thanks,
Sajjan Halarnkar

**Comment by craigmiller160** [comment] 2020-02-25 13:04
What's frustrating is I have a fix for this. I pulled down the code and found the problem. It's a silly bug. The "Network error" is meaningless, not sure why that's happening, but it's not related to the worklogs.

I have a PR that fixes this. I really would like the developer to pay attention and see it.

https://github.com/shridhar-tl/jira-assistant/pull/131

**Comment by DarkSlice1** [comment] 2020-02-28 10:45
@craigmiller160 could you tell me how to build your version in a CRX package so i can hand out to me team.
I cant see to get the NPM build working from the read me attached to the git repro - we've reverted back to 0.63 just get going again.

**Comment by shridhar-tl** [comment] 2020-02-28 17:35
Duplicate of #130 . Hence closing this issue. Track #130 for any updates.

**Closed by shridhar-tl** 2020-02-28 17:35 UTC
