### ISSUE TITLE
0.94 cannot login

### ISSUE THREAD

**Issue by StephanMeijer** [shridhar-tl/jira-assistant#121] opened 2020-02-17 10:42 UTC
<img width="503" alt="Screenshot 2020-02-17 at 11 40 59" src="https://user-images.githubusercontent.com/3169264/74646648-8a842f00-517a-11ea-82b0-05a2edd6d667.png">
<img width="668" alt="Screenshot 2020-02-17 at 11 43 06" src="https://user-images.githubusercontent.com/3169264/74646740-b4d5ec80-517a-11ea-84f1-cb095642c2a0.png">

<img width="590" alt="Screenshot 2020-02-17 at 11 43 49" src="https://user-images.githubusercontent.com/3169264/74646812-d3d47e80-517a-11ea-84ec-34cf1e6d5a03.png">

**Comment by StephanMeijer** [comment] 2020-02-17 10:43
<img width="668" alt="Screenshot 2020-02-17 at 11 43 06" src="https://user-images.githubusercontent.com/3169264/74646740-b4d5ec80-517a-11ea-84f1-cb095642c2a0.png">

**Comment by RomanChasovitin** [comment] 2020-02-17 11:14
@StephanMeijer I think, it's because JIRA Cloud API has been changed and the extension need to upgrade. I have the issue too. I look forward to an early update.

**Comment by Che994** [comment] 2020-02-18 04:50
Same issue :( 
![jira](https://user-images.githubusercontent.com/42790577/74704995-5707da00-5238-11ea-8dc0-537c5b582b11.png)

**Comment by sol3uk** [comment] 2020-02-18 08:33
https://github.com/shridhar-tl/jira-assistant/issues/119#issuecomment-586948792

**Comment by shridhar-tl** [comment] 2020-02-18 18:12
Duplicate of #119 . Refer to the #119  for updates.

**Closed by shridhar-tl** 2020-02-18 18:12 UTC
