### ISSUE TITLE
Unable to build project: `npm install` fails

### ISSUE THREAD

**Issue by jycr** [shridhar-tl/jira-assistant#202] opened 2021-11-03 14:39 UTC
Followed steps:
```
git clone https://github.com/shridhar-tl/jira-assistant.git
cd jira-assistant
git checkout develop
npm install
```

Displayed errors:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: jira-assistant@2.33.0
npm ERR! Found: primeflex@3.1.0
npm ERR! node_modules/primeflex
npm ERR!   primeflex@"^3.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer primeflex@"^1.0.0-rc.1" from jsd-report@0.1.9
npm ERR! node_modules/jsd-report
npm ERR!   jsd-report@"^0.1.9" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/john.doe/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/john.doe/.npm/_logs/2021-11-03T14_32_44_695Z-debug.log
```

See files in attachment:
- [/Users/john.doe/.npm/eresolve-report.txt](https://github.com/shridhar-tl/jira-assistant/files/7468321/eresolve-report.txt)
- [/Users/john.doe/.npm/_logs/2021-11-03T14_32_44_695Z-debug.log](https://github.com/shridhar-tl/jira-assistant/files/7468346/2021-11-03T14_32_44_695Z-debug.log)

**Comment by shridhar-tl** [comment] 2022-06-05 09:41
Unable to reproduce this issue anymore. Hence closing this issue.

Any way, if this issue occurs again in future, then as mentioned in the npm error "retry this command with --force, or --legacy-peer-deps"

**Closed by shridhar-tl** 2022-06-05 09:41 UTC
Labels: bug, unable to reproduce
