### ISSUE TITLE
Worklog entries removed from worklog calendar and report after upload

### ISSUE THREAD

**Issue by samsuits** [shridhar-tl/jira-assistant#242] opened 2022-11-16 21:01 UTC
**Basic Details**
- Jira Assistan Version : v2.42
- Browser & Version: Google Chrome Version 107.0.5304.87 
- OS: Ubuntu

**Describe the bug**
Worklog entries getting removed from worklog calendar after upload. This is happening specially with closed ticket. They are getting recorded but not more available to see in the worklog calendar for view. This is affecting worklog report as well. Worklog report not calculating tracking of closed ticket. I understand there is a setting in General -> Worklog -> 'Allow logging work on closed tickets', this is ticked as well. This is happening for both plugin and web version of jira assistant.

**To Reproduce**
Steps to reproduce the behaviour (if applicable / necessary):
1. Go to 'Jir Assistant'
2. Click on 'Workdlog Calendar from side menu'
3. Add a worklog by clicking on calendar. Add a worklog for closed ticket
4. Click on 'upload' button to upload worklog
5. The entry will be removed from calendar but it has been uploaded to Jira
6. The behaviour is same for plugin and web version

**Expected behavior**
The worklog entries should continue to appear on worklog calendar after upload for closed tickets
The worklog report should always calculate and report worklog entries for closed tickets

**Screenshots**
![image](https://user-images.githubusercontent.com/23556838/202293180-8b79a629-ceca-4734-8e03-1d3ee52b7e2d.png)
![image](https://user-images.githubusercontent.com/23556838/202293628-2445b8be-c450-4d2f-b4f2-ac63bd0057bf.png)

**Comment by shridhar-tl** [comment] 2022-11-17 03:39
Hi @samsuits - Thank you for reporting this issue, however, this is not an issue with Jira Assistant, but an issue with Jira indexing.

Multiple users had reported similar issues and every time this issue is because Jira server is not indexed properly. 
Please ask your Jira Admin to reindex the Jira server and that should resolve your issue. If you still face this issue after reindexing Jira, I will provide you with the steps to debug the issue. But as of now, I am pretty confident that it has nothing to do with Jira Assistant.

Here is one such random issue caused by Jira indexing: #61. There are several more reported so far.

**Comment by shridhar-tl** [comment] 2022-11-24 03:51
Hi @samsuits - Did the suggestion solve your issue?

**Comment by samsuits** [comment] 2022-12-04 20:19
Hi @shridhar-tl Thank you for response. We use cloud version of jira.
Will this solution work on cloud version as well ?

**Comment by shridhar-tl** [comment] 2022-12-05 04:42
Hi @samsuits, I believe cloud version would be automatically indexed regularly. So I don't think you will need to/would be able to index manually.

I'm using both cloud version and data center version as well and I don't see any such issues happening. I'm at this point clueless on what is happening. One think you can try is have network tab open before pushing the worklog from calendar and see what is the network requests going on and also see if there are any failures. It should try to pull the worklog for the selected date range and see if JIRA is responding with the appropriate tickets list.

That would be the next step to try. By the way, in first place are you still able to reproduce the issue?

**Comment by samsuits** [comment] 2022-12-05 19:45
@shridhar-tl Looks like the issue is with total number of work-logs jira-assistant can handle. We have some standard tickets to log admin and other common work-logs. One of those tickets has over 20,000 work-log entries. 
This is beginning of network response of one such ticket.
```json  
{"startAt":0,"maxResults":5000,"total":20087,"worklogs":[{...........}]
```
May be jira-assistant need to limit the response by filtering date-range ?

**Comment by shridhar-tl** [comment] 2022-12-20 13:21
Hi @samsuits - A fix has been provided to solve this issue and is now available in web version. For now to solve this issue, you can use Web version either by visiting https://app.jiraassistant.com or by clicking on "Switch to Web" menu under "WEB" badge on top right corner of Jira Assistant.

In around a weeks time, I will try and publish the updates to extension users.

**Comment by shridhar-tl** [comment] 2022-12-27 15:53
This implementation is done and hence closing this issue. This change is already available in Web version and you would start seeing the changes in Extension and Cloud App once you are updated to JA v2.44.

**Closed by shridhar-tl** 2022-12-27 15:53 UTC
Labels: bug, in live testing

**Comment by samsuits** [comment] 2023-01-08 22:32
Wonderful. Web version looks good. Thanks for fixing it !!
