### ISSUE TITLE
Youtube image link in the way of the whole UI

### ISSUE THREAD

**Issue by RobbeVer** [shridhar-tl/jira-assistant#318] opened 2023-08-17 11:30 UTC
### Checklist before you being

- [X] I am sure that I am already using latest version of Jira Assistant
- [X] I had verified that, no similar issues are already reported in [issue tracker](https://github.com/shridhar-tl/jira-assistant/issues)
- [X] I had tried reproducing this issue with with [Web version of Jira Assistant](https://app.jiraassistant.com) to ensure that this issue is not recently fixed and yet to be published
- [X] I had verified that, my query is not answered in [FAQ section of website](https://www.jiraassistant.com/faq)
- [X] I had verified that, my issue is not listed as [known bugs in website](https://www.jiraassistant.com/version-history)

### How do you use Jira Assistant?

Browser extension

### Are you using cloud version of Jira or self hosted (data center / server) of Jira.

Self hosted (datacenter)

### Version of Jira Assistant

2.54

### What browser are you using?

Opera

### What OS are you using? You need not disclose this if you feel it is irr-relevant for your issue.

Windows

### Bug Description

Since the newest update there is an entire youtube logo/link blocking the view of the tool. I can use the tool by manually deleting the HTML element. The issue does not seem to reproduce on chrome:
![image](https://github.com/shridhar-tl/jira-assistant/assets/62553772/24df22f4-0e46-4146-96d0-f5fcfc410b64)

### Checklist before you submit

- [X] I have ensured not to paste any confidential information like Jira url, Mail id, etc.
- [X] I have verified my browser console logs and added necessary details (if required)
- [X] I have added required screenshots if the bug is related to UI (as necessary)

**Comment by shridhar-tl** [comment] 2023-08-21 03:37
Hi @RobbeVer - Sorry for the inconvenience, however I was not able to reproduce it in any browser.

Not just with Opera, I have tried with Chrome, Edge, Firefox and Vivaldi also and everywhere it works well.

So can you please provide me with the exact browser version (not JA version) so that I will try to see if that specific version has any issues.

![image](https://github.com/shridhar-tl/jira-assistant/assets/37339683/960911c3-dd55-4bc1-bc2e-006fc78628b0)

**Comment by shridhar-tl** [comment] 2023-08-21 04:31
Hi @RobbeVer - You can try using the Web version using the following Url and see if it works well for you. If it works well, then you can continue to use it till the time new updates are published to Extension. Also let me know if it works well in Web so that I will know the change I did fixes the issue or not.

Web Version of JA: https://app.jiraassistant.com/?authType=1

You need not do any separate authentication in web version. Still authentication is taken care by Extension itself while web is just used to display the page. So Web helps you use latest code with bug fixes without compromising on any aspects.

You can also permanently switch to Web so that just in case of such issues, you will know in advance even before I publish the extension so that the issue can be reported and immediately I would be able to resolve it.

Once the changes are published to extension, it takes time to push another version due to various limitations.

To know more about Web version, you can have a look into following Urls:
https://www.jiraassistant.com/install-options/
https://www.jiraassistant.com/why-web-version/

**Comment by ch-fuchs** [comment] 2023-08-28 07:17
Good morning,

I can reproduce the same issue (screenshot see below).

FF: 102.14.0esr (64-bit)
JA: v2.54

Temporary work around which works is to remove the node on the dom (source code) using the inspector. As long as you dont refresh the page, it works because UI is not rerendered with each call. Would be happy if it was fixed.

Thanks!

See screenshot:
![Bug_JiraAssist_youtubeImage](https://github.com/shridhar-tl/jira-assistant/assets/109806712/f25c9a92-ee82-42b8-8c4c-3f15fde14548)

**Comment by ch-fuchs** [comment] 2023-08-29 07:21
@shridhar-tl Tried the web version and the fix works - no more big youtube image upon login. Thanks!

Switching to the web version seems like an easy win, but (some of) our customers might be worrying about data protection as all JIRA data would be visible to your web platform. Anyways, thanks for the advice and the fix!

**Comment by shridhar-tl** [comment] 2023-08-30 16:02
@ch-fuchs - Thank you for confirming the fix works. Will try to publish the fixes ASAP.

When you talk about data protection in Web version, let me clarify you few points:
1.  Source code is same for Web and Extension.
2.  There is no backend server as such which is hosting this Web version. The web version is hosted within the Git Repository itself. And this is the repository which is hosting Web version. If you are not aware about GitHub pages, you can learn more about it which would give you a very good clarity on the data security part.
3. When you switch to Web version, nothing changes in how your data is handled. The data is still within your extension's cache. It does not go out anywhere.
4. It is absolutely equivalent as that of using extension except for the fact that Web uses latest code. In no way there is any technical difference between these two.

You can learn further about it under Data Security section in following url: https://www.jiraassistant.com/why-web-version/

**Comment by shridhar-tl** [comment] 2023-09-05 05:26
The fix has been published for extension users and is already available for Firefox store. For other browsers it is still being reviewed. You should see it soon within a week max.

Closing this ticket as this issue is resolved and is being published for extension users as well. Once your extension version gets updated to v2.55, you should see it working.

**Closed by shridhar-tl** 2023-09-05 05:26 UTC
Labels: bug, awaiting input, ready for release
