### ISSUE TITLE
Error opening the Worklog Report

### ISSUE THREAD

**Issue by kusd24** [shridhar-tl/jira-assistant#130] opened 2020-02-21 12:43 UTC
Please fix the error opening the Worklog Report. The error occurs since version 0.94 and higher in Chrome. 

![image](https://user-images.githubusercontent.com/61314664/75035351-d9ff8d80-54e1-11ea-908f-6fc0b1d60c24.png)
![image](https://user-images.githubusercontent.com/61314664/75035572-5a25f300-54e2-11ea-9d61-46293488e5cc.png)

**Comment by DarkSlice1** [comment] 2020-02-21 12:53
error in console 

`index.d3118521.chunk.js:1 Unhandled rejection (promise:  Promise {<rejected>: TypeError: Cannot read property 'logData' of null
    at chrome-extension://momjbjbjpbcbnepbgkkiaof…} , reason:  TypeError: Cannot read property 'logData' of null
    at 3.52bc2233.chunk.js:1
    at index.d3118521.chunk.js:1
    at Array.forEach (<anonymous>)
    at Array.union (index.d3118521.chunk.js:1)
    at 3.52bc2233.chunk.js:1
    at index.d3118521.chunk.js:1
    at Array.forEach (<anonymous>)
    at Array.union (index.d3118521.chunk.js:1)
    at t.value (3.52bc2233.chunk.js:1)
    at 3.52bc2233.chunk.js:1 ).
value @ index.d3118521.chunk.js:1
(anonymous) @ index.d3118521.chunk.js:1
3.52bc2233.chunk.js:1 Uncaught (in promise) TypeError: Cannot read property 'logData' of null
    at 3.52bc2233.chunk.js:1
    at index.d3118521.chunk.js:1
    at Array.forEach (<anonymous>)
    at Array.union (index.d3118521.chunk.js:1)
    at 3.52bc2233.chunk.js:1
    at index.d3118521.chunk.js:1
    at Array.forEach (<anonymous>)
    at Array.union (index.d3118521.chunk.js:1)
    at t.value (3.52bc2233.chunk.js:1)
    at 3.52bc2233.chunk.js:1`

**Comment by craigmiller160** [comment] 2020-02-21 13:14
I second this. Also the Calendar view is broken. No errors in the console but it doesn't display any of the worklogs.

**Comment by craigmiller160** [comment] 2020-02-21 15:23
I added a code change in another issue that I believe MAY fix this too, but I've done far less testing on that:

https://github.com/shridhar-tl/jira-assistant/issues/128#issuecomment-589693305

**Comment by shiennguyen** [comment] 2020-02-22 10:53
![image](https://user-images.githubusercontent.com/10023168/75091069-037cef80-559c-11ea-956f-0e831799adbc.png)
although have responded data, but they don't show on the UI

**Comment by craigmiller160** [comment] 2020-02-22 11:03
> ![image](https://user-images.githubusercontent.com/10023168/75091069-037cef80-559c-11ea-956f-0e831799adbc.png)
> although have responded data, but they don't show on the UI

Yep. My PR will fix this. Just need it to be seen and merged. Hope the dev here sees it soon.

https://github.com/shridhar-tl/jira-assistant/issues/128#issuecomment-589693305

**Comment by shridhar-tl** [comment] 2020-02-28 17:50
Duplicate of #126 . Hence closing this issue. You can track for any updates through #126. Also v0.97 is already available in Firefox and should fix all the issues mentioned. For chrome it would take some time for the review to be completed by Google and hence expected date for the update to be available for chrome users is 3rd of March 2020.

**Closed by shridhar-tl** 2020-02-28 17:50 UTC

**Comment by kusd24** [comment] 2020-03-01 08:46
Error fixed in FF 0.97. Thanks.
Waiting for an update for Chrome
