### ISSUE TITLE
0.94 fix for user names does not work for reports

### ISSUE THREAD

**Issue by foxel** [shridhar-tl/jira-assistant#120] opened 2020-02-17 04:25 UTC
I've built 0.94 version for Chrome and it's working unless you are working with worklog data of another users.
Adding user to user groups don't work as response does not contain e-mails:
```json
[
    {
        "self": "https://***/rest/api/2/user?accountId=***",
        "accountId": "***",
        "accountType": "atlassian",
        "emailAddress": "",
        "avatarUrls": {
            "48x48": "***",
            "24x24": "***",
            "16x16": "***",
            "32x32": "***"
        },
        "displayName": "***",
        "active": true,
        "timeZone": "Asia/Tomsk",
        "locale": "en_US"
    }
]
```

My temporary fix for getUserName:
```javascript
export function getUserName(userObj, convertToLower) {
    let name = null;
    if (typeof userObj === "object") {
        name = userObj.name || userObj.emailAddress || userObj.accountId;
    }

    if (convertToLower && name) {
        name = name.toLowerCase();
    }

    return name;
}
```

**Comment by shridhar-tl** [comment] 2020-02-18 18:11
Duplicate of #119 . Refer to the #119  for updates.

**Closed by shridhar-tl** 2020-02-18 18:11 UTC
