### ISSUE TITLE
Calendar/Worklog should adhere to time display settings

### ISSUE THREAD

**Issue by Regenhardt** [shridhar-tl/jira-assistant#146] opened 2020-04-06 06:10 UTC
Currently, the tiles in Calendar/Worklog always show 12h-times. This is very confusing to anyone outside america.   
The datetime picker at the top already adheres to the time display setting. Only the tiles in the calendar still show 12h times.

Edit: On Firefox.

**Comment by Regenhardt** [comment] 2020-04-06 06:39
If you can tell me where to find that control, I might just make a Pull Request myself. I'm not actually a frontend developer, but you also fixed this in the datetime picker so I would probably try to mimic that.

**Comment by shridhar-tl** [comment] 2020-04-07 04:44
I will check and let you know. I think this should be a small fix and I can do it myself. But unfortunately even if this is fixed, I am not sure when I will be able to publish it. 

Their are some issues with publishing a new version to both Chrome and Firefox store where still I am trying to identify the cause. I had contacted store dev support multiple times and no reply so far. May be due to current lock-down situation, their isn't much support available. 

Their are already multiple fixes ready to be published, but due to this issue still unable to publish. Hence I expect you to wait some time for the issues to get resolved. Same is applicable for me as I am awaiting reply from web store dev support team.

**Comment by shridhar-tl** [comment] 2020-04-08 16:07
@Regenhardt - For now fixed issue with showing AM / PM and 12 / 24 hour format changes based on settings. But still seperator between hour and minute is always used as ":". This does not change based on settings as that adds unnecessary complexity for this case.

Still it would take some time for publishing process due to the current lockdown situations as mentioned earlier.

Hope that helps.

**Comment by shridhar-tl** [comment] 2020-04-30 04:10
I am still facing issue publishing to Chrome web store. But latest updates (i.e. v1.3) are published to Firefox, Edge and Opera already. Hope all the issues with Firefox should have already got resolved by now.

Chrome users please be patient or use Firefox version temporarily to help with your activities. Apologies for all the inconvenience caused.

**Closed** 2020-07-06 04:58 UTC
Labels: bug, in live testing
