### ISSUE TITLE
Weekly and  monthly views show different values

### ISSUE THREAD

**Issue by futak** [shridhar-tl/jira-assistant#61] opened 2018-10-01 14:50 UTC
We've recently noticed that in the Worklog [User - Day wise] report, the reported hours for the exact same dates seem to be different in weekly and monthly views.
For example, check 27-Sep-2018 on the following screenshots:
Last week - no logged work is visble for any of the users:
![last_week](https://user-images.githubusercontent.com/19271303/46295448-5c5b7a80-c598-11e8-9db2-4ccc04b2f92f.png)
Last month - logged work is visible for all three users:
![last_month](https://user-images.githubusercontent.com/19271303/46295481-7432fe80-c598-11e8-9151-ae3d66346be1.png)

The users are the same and are in the same order on the two images. The screenshots were taken a few seconds apart.

**Comment by shridhar-tl** [comment] 2018-10-10 02:14
Hi @futak , thank you for reporting this issue. I had a initial look at the report and I and my team couldn't reproduce this issue. I will have a deeper look into it and see if their are any possibility for this to happen.

At the mean time you can directly query your Jira server and see if Jira is providing appropriate tickets with the query. You can expand the report to ticket view and compare the tickets list in both monthly and weekly view for a single day and see what are the tickets missing in weekly view. then you can see if that ticket is provided by jira when you query the data for a single date. Instead of querying you can also check the data from the network tab when you generate the report.

Some times this happens with the Jira Server if indexing is not proper in Jira. So once you verified it with the query, if you find any differences then you can contact your Jira admin to reindex the db to get it working well. If you don'd find any issue with Jira server then get back to me with your observations if any.

**Comment by futak** [comment] 2018-10-10 07:37
Thank you for your suggestion! Re-indexing the database seems to have fixed the issue.

**Comment by shridhar-tl** [comment] 2018-10-11 03:06
As the issues is resolved by re-indexing the Jira server, closing this issue.

**Closed by shridhar-tl** 2018-10-11 03:06 UTC
Labels: bug
