### ISSUE TITLE
Jira Assistant no longer opens in Chrome based Vivaldi Browser

### ISSUE THREAD

**Issue by NeoMatrixJR** [shridhar-tl/jira-assistant#210] opened 2022-02-24 14:50 UTC
This started some time ago...sorry...I'm not sure exactly when.  I used to use this in my Vivaldi browser, but for some time it's just been opening a blank screen.  Works fine in Chrome and Edge, but Vivaldi is my daily driver.  Have tested on multiple PCs.

**Comment by shridhar-tl** [comment] 2022-06-07 08:13
Hi @NeoMatrixJR Thank you for reporting this issue. This addon was not tested with Vivaldi so far and so it is not a supported browser.

Still I tried to look into this issue and identified that now Vivaldi is not opening the appropriate url in window.open call. But if I debug then all works fine. Not sure what is causing this issue, but mostly it looks like issue with Vivaldi itself and not in code. So I am not sure when I would be able to solve this issue.

I would suggest using chrome, but just in case if anyone still wants to use vivaldi only, then as a temporary workaround, try bookmarking the following url and accessing it directly which works:

chrome-extension://momjbjbjpbcbnepbgkkiaofkgimihbii/index.html

**Comment by lbarbaglia** [comment] 2022-08-31 13:20
**Basic Details:**
- 2.41
- Firefox 104.0.1
- Windows 11

**Describe the bug**
When I try to open Jira Assistant from the extension button, it opens a blank page.

**To Reproduce**
Steps to reproduce the behavior (if applicable / necessary):
1. Click on "JA" button
2. Blank page appears instead on the UI
Note: It's opening on the web app instead of the usual moz-extension://xxxxxxxxxxx

**Screenshots**
![image](https://user-images.githubusercontent.com/35603025/187687261-096e433b-1af2-4867-b2f2-e6c4698cbdea.png)

**Other details**
I noticed an error in the console:
![image](https://user-images.githubusercontent.com/35603025/187687478-4684ade3-ef13-46ab-9c5e-128bd74aa92e.png)

This issue appeared today, yesterday I was able to use it correctly.
I was wondering if I should open an another issue since it's Firefox and not a Chrome based browser but I put it here instead.

If you need any more information, let me know.

**Comment by shridhar-tl** [comment] 2022-09-02 04:13
Hi @lbarbaglia - Initially I missed your issue as it is under different title and so there was delay in resolving it. However thank you for reporting this issue with screenshot which helped me to identify and resolve the issue without much effort.

Primarily you would have switched to Web version and that is the reason it is loading Web version of JA always. You can switch back to Extension any time by once again click on Web from top right corner of the page.

Due to continuous build and publish, Web version could be unstable at times like this. But if this issue has been published to extension, then providing the solution could have taken much longer time due to the publish process. So as you were using web version and reported the issue before it is being published to extension, I was able to provide quick fix for this. Hence I would request you continue to use the Web version. If you face any issues, you can switch back any time.

**Comment by shridhar-tl** [comment] 2022-09-02 04:14
@NeoMatrixJR - You can also try using the Web version of JA in Vivaldi by accessing https://app.jiraassistant.com. If you have the extension already installed, then Web version would connect with extension and would work well.

**Closed** 2022-09-02 04:32 UTC
Labels: bug, help wanted, blocked
