### ISSUE TITLE
Open Ticket JQL is not editable

### ISSUE THREAD

**Issue by ChrisM-1231** [shridhar-tl/jira-assistant#324] opened 2023-09-07 16:33 UTC
### Checklist before you being

- [X] I am sure that I am already using latest version of Jira Assistant
- [X] I had verified that, no similar issues are already reported in [issue tracker](https://github.com/shridhar-tl/jira-assistant/issues)
- [X] I had tried reproducing this issue with with [Web version of Jira Assistant](https://app.jiraassistant.com) to ensure that this issue is not recently fixed and yet to be published
- [X] I had verified that, my query is not answered in [FAQ section of website](https://www.jiraassistant.com/faq)
- [X] I had verified that, my issue is not listed as [known bugs in website](https://www.jiraassistant.com/version-history)

### How do you use Jira Assistant?

Browser extension

### Are you using cloud version of Jira or self hosted (data center / server) of Jira.

Cloud Jira

### Version of Jira Assistant

2.54

### What browser are you using?

Edge

### What OS are you using? You need not disclose this if you feel it is irr-relevant for your issue.

Windows

### Bug Description

Unable to edit the Open Ticket JQL, all typing is ignored.

### Checklist before you submit

- [X] I have ensured not to paste any confidential information like Jira url, Mail id, etc.
- [X] I have verified my browser console logs and added necessary details (if required)
- [X] I have added required screenshots if the bug is related to UI (as necessary)

**Comment by shridhar-tl** [comment] 2023-09-15 01:38
Hi @ChrisM-1231 ,
This is duplicate of #158 and #246. You will get your answer in that ticket.

Additionally, a search with keywords in official website may some times provide you with quick answer. Following search results include a FAQ which answers this question as well:

https://jiraassistant.com/search/open%20tickets%20jql%20not%20editable/

Closing this ticket assuming your issue is resolved. Please feel free to get back to me for any other queries.

**Closed by shridhar-tl** 2023-09-15 01:38 UTC
