### ISSUE TITLE
Add Worklog screen: Set the field "Log time" to the current time instead of the default 12:00 AM

### ISSUE THREAD

**Issue by oualid-code** [shridhar-tl/jira-assistant#226] opened 2022-08-21 11:37 UTC
This enhancement will reduce the number of clicks to add worklog via the "Add Worklog" screen.
Thank you!

**Comment by shridhar-tl** [comment] 2022-09-15 05:02
Hi @oualid-code , from which screen do you see 12AM as default? In add worklog popup I see current time is only displayed. I am not sure where else you see 12AM as default time. Please provide some snapshots or steps to reproduce.

![image](https://user-images.githubusercontent.com/37339683/190317819-0a489b95-2cf7-45c8-992c-3032dc9c6725.png)

**Comment by casper-81** [comment] 2022-09-16 21:40
Hi @shridhar-tl , I can help on this one.

Default 12:00am happens if you right click on a day and add an worklog from it. For e.g. from the Daywise worklog:

![image](https://user-images.githubusercontent.com/110611435/190793904-752d5048-d03e-47fc-8e1f-8b8c68f63925.png)

Cheers m8 :)

**Comment by oualid-code** [comment] 2022-09-29 13:11
Thank you @casper-81.

Hi @shridhar-tl,

Default 12:00am appears also when trying to add worklog in the "Worklog Report" screen:

![image](https://user-images.githubusercontent.com/5104422/193040262-6eec404a-20f4-4713-b931-61f07fce1fe8.png)

Thank you and regards,

**Comment by shridhar-tl** [comment] 2022-10-02 04:35
Thank you @oualid-code and @casper-81 for providing more information, It was intentionally done so from both those modules because you can log work for any date from those modules. Hence logging for current time did not really made sense there.

Also in most of the use cases, worklog would be added only after the task is completed or at the end of the day, so you would need to change the time to past in most of the use cases.

However, if you think it is helping on some cases, implementing this change is not making anything worse. So will have a look at it and implement it ASAP.

**Comment by shridhar-tl** [comment] 2022-12-27 15:51
I hope this issue is resolved long back. If you are still facing any issue, please feel free to reopen this issue or raise a new one. As of now I am closing this issue considering its fixed.

**Closed by shridhar-tl** 2022-12-27 15:51 UTC
Labels: enhancement, in live testing
