### ISSUE TITLE
Add "Components" field to worklog

### ISSUE THREAD

**Issue by alexpol97** [shridhar-tl/jira-assistant#77] opened 2019-06-21 10:37 UTC
Hi!
Can I add to the worklog a display of the "Components" field from the tasks? If possible, they should also be uploaded to csv.

**Comment by shridhar-tl** [comment] 2019-09-04 16:17
This is duplicate of #51 and hence closing this issue. Please track the status in initial ticket.

**Closed by shridhar-tl** 2019-09-04 16:17 UTC
Labels: duplicate, enhancement
