### ISSUE TITLE
New feature: Allow selecting the current Active Sprint time range in the Worklog date range menu

### ISSUE THREAD

**Issue by Kimamisa** [shridhar-tl/jira-assistant#58] opened 2018-09-27 09:58 UTC
**As** a Scrum Master
**I want** to be able to display an overview of the reported time over the sprint duration

PS: I love the work you did for this plugin, thank you !

**Comment by shridhar-tl** [comment] 2019-09-14 08:36
Duplicate of #6

**Closed by shridhar-tl** 2019-09-14 08:36 UTC
Labels: duplicate
