### ISSUE TITLE
New workload report does not show data for some users

### ISSUE THREAD

**Issue by jrupik** [shridhar-tl/jira-assistant#253] opened 2023-01-05 07:22 UTC
### Checklist before you being

- [X] I am sure that I am already using latest version of Jira Assistant
- [X] I had verified that, no similar issues are already reported in [issue tracker](https://github.com/shridhar-tl/jira-assistant/issues)
- [X] I had tried reproducing this issue with with [Web version of Jira Assistant](https://app.jiraassistant.com) to ensure that this issue is not recently fixed and yet to be published
- [X] I had verified that, my query is not answered in [FAQ section of website](https://www.jiraassistant.com/faq)
- [X] I had verified that, my issue is not listed as [known bugs in website](https://www.jiraassistant.com/version-history)

### How do you use Jira Assistant?

Browser extension

### Are you using cloud version of Jira or self hosted (data center / server) of Jira.

Self hosted (datacenter)

### Version of Jira Assistant

2.44

### What browser are you using?

Firefox

### What OS are you using? You need not disclose this if you feel it is irr-relevant for your issue.

Windows

### Bug Description

New workload report (standard - not modified) does not show data for one user, old report shows (also not modified). I am using plugin without any modifications - only i created a user group.
![old-workload-panel](https://user-images.githubusercontent.com/39516335/210723584-6cf85328-0867-4f53-9801-68d709574348.png)
![new-workload-panel](https://user-images.githubusercontent.com/39516335/210723641-38b35deb-7153-46cd-9424-a473fc829e36.png)

### Checklist before you submit

- [X] I have ensured not to paste any confidential information like Jira url, Mail id, etc.
- [X] I have verified my browser console logs and added necessary details (if required)
- [X] I have added required screenshots if the bug is related to UI (as necessary)

**Comment by shridhar-tl** [comment] 2023-01-05 15:53
Hi @jrupik - Thank you for reporting this issue. However I have tried this by multiple different ways and I was not able to reproduce this issue. Can you verify couple of things from your end?

1. First thing is to look at what is the settings in Log filter and JQL filter tab of New worklog report settings page. See if you have "Show all worklogs" selected under Log filter tab and JQL filter must be empty. I understand you mentioned you did not change any default settings, but I would like to verify some basic things first before getting into anything else.
![image](https://user-images.githubusercontent.com/37339683/210821891-60fe9bb9-1feb-4539-9311-f37db5d8b4f1.png)


2. If above step is proper, then try to just have only 1 group with just that user and see what is populated. While doing that have network tab open and see what is the request url and what is the response from Jira. If possible send me the screenshot after hiding any confidential information from the screenshot.
Note: From Web version you wont be able to check any network logs as all the http requests are routed through the extension if it is installed. So try this step from extension.

Based on what is the outcome of these try, let us think further.

**Comment by shridhar-tl** [comment] 2023-01-05 17:22
Also can you verify if the user for whom worklog is not pulled in new report have logged on some issues which is having lots of worklogs, say like more than 5000 worklogs in a single issue?

**Comment by jrupik** [comment] 2023-01-09 07:20
> Hi @jrupik - Thank you for reporting this issue. However I have tried this by multiple different ways and I was not able to reproduce this issue. Can you verify couple of things from your end?
> 
>     1. First thing is to look at what is the settings in Log filter and JQL filter tab of New worklog report settings page. See if you have "Show all worklogs" selected under Log filter tab and JQL filter must be empty. I understand you mentioned you did not change any default settings, but I would like to verify some basic things first before getting into anything else.
>        ![image](https://user-images.githubusercontent.com/37339683/210821891-60fe9bb9-1feb-4539-9311-f37db5d8b4f1.png)
> 

Yes

>     2. If above step is proper, then try to just have only 1 group with just that user and see what is populated. While doing that have network tab open and see what is the request url and what is the response from Jira. If possible send me the screenshot after hiding any confidential information from the screenshot.
>        Note: From Web version you wont be able to check any network logs as all the http requests are routed through the extension if it is installed. So try this step from extension.
> 
> 
> Based on what is the outcome of these try, let us think further.

The same issue - One group with one user (the same user with problems)- no data on "grouped" tab, but data for that user are visible on "Flat (groupavle)" tab

**Comment by jrupik** [comment] 2023-01-09 07:21
> Hi @jrupik - I have the same issue on #254. In my testing data for the New and Old Reports is identical when viewing the Flat (Groupable) tabs, do you see the same?

Yes, I checked it and yes, no data on "grouped" tab, but data for that user are visible on "Flat (groupable)" tab.

**Comment by jrupik** [comment] 2023-01-09 14:16
> Also can you verify if the user for whom worklog is not pulled in new report have logged on some issues which is having lots > of worklogs, say like more than 5000 worklogs in a single issue?
No, it is not an issue.

**Comment by shridhar-tl** [comment] 2023-02-19 14:57
I am finding it very hard to reproduce this issue. If anyone else is facing this issue, please contact me and I would like to know if you were able to provide some clue to identify the root cause. You can either provide the details here or contact me via email.

**Comment by shridhar-tl** [comment] 2023-03-06 04:33
Hi @jrupik @peterwatersfis - I consider this issue is resolved and is available in JA v2.48. It is already available for Chrome and Firefox users. For Edge it would soon be published. You can either upgrade to latest version or test it with web version.

However I'm closing this issue considering it is resolved. If you still face any issue, please feel free to reopen it.

**Closed by shridhar-tl** 2023-03-06 04:33 UTC
Labels: bug, help wanted, awaiting input
