### ISSUE TITLE
Network error: Continuously getting this error even if connect to network 

### ISSUE THREAD

**Issue by yogeshjain009** [shridhar-tl/jira-assistant#133] opened 2020-02-25 12:09 UTC

**Comment by craigmiller160** [comment] 2020-02-25 13:05
Not sure why that's happening, it doesn't seem to actually interfere with the operation of the app. I've fixed the ongoing problems myself, but the dev has yet to approve my PR. It's a really easy change.

**Comment by shridhar-tl** [comment] 2020-02-28 17:50
Duplicate of #126 . Hence closing this issue. You can track for any updates through #126. Also v0.97 is already available in Firefox and should fix all the issues mentioned. For chrome it would take some time for the review to be completed by Google and hence expected date for the update to be available for chrome users is 3rd of March 2020.

**Closed by shridhar-tl** 2020-02-28 17:50 UTC

**Comment by yogeshjain009** [comment] 2020-02-28 17:58
Can you please share url for Firefox add-on as I was not able find one with same name.

Thanks and Regards
Yogesh Jain
________________________________

**Comment by shridhar-tl** [comment] 2020-02-29 15:39
@yogeshjain009 - It is available in following document.

https://github.com/shridhar-tl/jira-assistant#jira-assistant
