### ISSUE TITLE
JA gets stuck while logging in with "Authorizing", "Setting Up", or "Loading"

### ISSUE THREAD

**Issue by NODeeJay** [shridhar-tl/jira-assistant#333] opened 2023-10-06 11:53 UTC
### Checklist before you being

- [X] I am sure that I am already using latest version of Jira Assistant
- [X] I had verified that, no similar issues are already reported in [issue tracker](https://github.com/shridhar-tl/jira-assistant/issues)
- [X] I had tried reproducing this issue with with [Web version of Jira Assistant](https://app.jiraassistant.com) to ensure that this issue is not recently fixed and yet to be published
- [X] I had verified that, my query is not answered in [FAQ section of website](https://www.jiraassistant.com/faq)
- [X] I had verified that, my issue is not listed as [known bugs in website](https://www.jiraassistant.com/version-history)

### How do you use Jira Assistant?

Jira cloud App

### Are you using cloud version of Jira or self hosted (data center / server) of Jira.

Cloud Jira

### Version of Jira Assistant

4.7.0

### What browser are you using?

Not applicable

### What OS are you using? You need not disclose this if you feel it is irr-relevant for your issue.

Others

### Bug Description

Browsers: Chrome, Brave, Firefox, Edge
OS: Windows 10 LTSC 22H4, Windows 11, Tumbleweed Linux, Ubuntu 22.04 LTS, MacOS
long story short, we use all kind of OS on browser versions in the company, everyone has the issue.

Since last week we are stuck at the same point receiving different failure messages. To reproduce:

1.	Open the Jira instance
2.	Click on apps
3.	Click on JA
5.	It gets stuck with either "Authorizing", "Setting Up" or "Loading"

We also tried the other options from Jira Assistant, in the end we tried:

*	As app in Jira Cloud
*	As Webapp from the website https://app.jiraassistant.com/integrate
*	As browser plugin

Now, as plugin it works, because it reuses the session from the browser. After we reinstalled it as Jira App, I would have expected the authorization again, but it does not come. I could imagine this is the issue or somewhere there at the auth.

However, we can't really use it as browser plugin because we use around 9 different browsers in the company and many people use Safari and there is no plugin for Safari other than the App in Jira itself.

I contacted Jira support, and as usual they defer their responsibility. We exchanged HAR files and the Jira support came up with:

```
I could replicate the same issue in my test instance as well and App keeps loading and not moving forward.

While analyzing the HAR files and logs we see few errors like below where the App is trying to fetch nonexisting preference key using the endpoint /rest/api/3/mypreferences?key=jira.user.theme.custom-nav-bar-section-message.dismissed  
Request URL:[https://clever-system.atlassian.net/rest/api/3/mypreferences?key=jira.user.theme.custom-nav-bar-section-message.dismissed]

Request Method:GET

Status Code:404

Remote Address:185.166.143.37

As this is a third-party add-on [Jira Assistant, ](https://www.jiraassistant.com/)we do have much information on why the above endpoint was called and if it is needed for the configuration.

Next Steps:
Since this Add-on is supported by the Vendor , Vendor support team is the one that has the expertise on how to configure it correctly. I would recommend you to contact them by accessing their [Contact Us Portal](https://www.jiraassistant.com/contact-us/). It seems that they have 2 main options.

[... issue tracker and google doc links ...]

As they have direct access to source code and development resources that are outside of our reach, I’m confident that the vendor would be best equipped to provide you with further assistance.

Of course, if there’s anything you would need on our side (if they recommend any Cloud-specific actions to be taken or sysadmin functions to be performed), please don’t hesitate to reach out to us. We’ll be happy to help you out if need be!

Thanks and Regards,
Arvind Kishore D | Atlassian Cloud Support
```

Additionally I have the HAR files, I could send you, but they are full of internal information and I would need hours to sanitize them to upload them here.

From a technical perspective, as we did not update JA for several weeks, I don't really believe it's an issue with JA, but I also don't have the expertise to verify this quickly or would be able to proof to Atlassian support. Any ideas how I can troubleshoot this further?

Thanks,
Alex

### Checklist before you submit

- [X] I have ensured not to paste any confidential information like Jira url, Mail id, etc.
- [X] I have verified my browser console logs and added necessary details (if required)
- [X] I have added required screenshots if the bug is related to UI (as necessary)

**Comment by shridhar-tl** [comment] 2023-10-09 03:38
Hi @NODeeJay, Thank you for contacting us and sorry for any inconvenience caused. There are multiple questions which I would like to answer:

First of all, Jira support team is right that they won't be able to help you with issues related to Add-on and that has to be taken care by Vendor only. They do not have enough information related to any Addons and we cannot expect them to resolve such issues.

Second thing about the HAR files. I won't really need HAR files and don't take effort sanitizing that.

Instead, when this issue happens, please take the console screenshot and send it over to me which would help me with identifying the root cause.

I see Jira support stating the usage of "/rest/api/3/mypreferences" api and that resulting in 404 error. However, that API is not at all used by Jira Assistant. That must be error from something else. Any way console screenshot would be very much helpful.

Also please let me know:

1. If you have tried with any other browser? I see you mentioned you use multiple browsers in your organization. But just thought of checking if you have personally tried more than 1 browser.
2. Is it only you who is facing this issue or no one in your organization is able to use it?
3. If possible can you try using it in incognito mode once and see if it works.

I would like to see the console screenshot and answers to above questions to first understand if this issue is happening because of browser or because of some server configuration.

**Comment by shridhar-tl** [comment] 2023-10-09 04:01
Hi @NODeeJay  - I don't know if it really helps, but I have just published a new version to give a try and you should have it automatically updated as there are not major changes.

So retry the steps mentioned above and let me know the status. Thank you.

**Comment by NODeeJay** [comment] 2023-10-09 07:28
Hi Shridhar,

thanks for getting back to me that quickly. It seem to have automatically updated to v 4.8.0.
The app still loads with Setting up... Please wait...

in the network tab I see 
![image](https://github.com/shridhar-tl/jira-assistant/assets/83764033/a6f757c0-5f06-489d-a320-ed008f10df1f)

The console with the dismissed part the Atlassian support mentioned
![image](https://github.com/shridhar-tl/jira-assistant/assets/83764033/83d5763d-4e2a-4e4c-9865-db5b0b4bc0c4)

![image](https://github.com/shridhar-tl/jira-assistant/assets/83764033/cd615aa7-ab78-4d4b-9d5d-8f10a980274b)

here is another part whith a source map error:
![image](https://github.com/shridhar-tl/jira-assistant/assets/83764033/5f8c6dfa-d19d-4841-9677-3a01d882fd5c)

Yes, also I tried several ones, FF, Brave and Edge. It's everyone, it started with some colleagues and until last Thursday it spread to all users.
I tried InPrivate but it looks similar
![image](https://github.com/shridhar-tl/jira-assistant/assets/83764033/d8049f8f-e90f-4b51-bda5-1fc77cd64d03)


How else could I help investigate?

Thanks,
Alex

**Comment by NODeeJay** [comment] 2023-10-09 11:39
Jira support recommended to use the webapp and OAuth2 there. I tried, interestingly it does not work in FF but in Edge
In Edge it produces, but works once.
![image](https://github.com/shridhar-tl/jira-assistant/assets/83764033/6ca0aef7-8f33-40ed-9a48-171ddd9d2285)
When I then try to hop over to the JA as app it gets stuck there again.

in FF I get
![image](https://github.com/shridhar-tl/jira-assistant/assets/83764033/75e6a3d8-46f9-4892-a010-98e7d4b08920)
and get stuck at "Loading"

**Comment by shridhar-tl** [comment] 2023-10-09 13:25
Hi @NODeeJay , Thank you for detailed description and screenshots.

**Response for your first post:**
1. About the API call failure for my-preference API: This API call is not done by Jira Assistant. This could be internal to Jira itself. Additionally such API call happens even in my instance of Jira and that is also failing. But failure of this API call is not impacting Jira Assistant in any way and you can safely ignore this.
2. The source map error you reported is not relevant to Jira Assistant. These could be Jira's internal and once again can be ignored.
3. Thank you for trying with different browser and confirming. This confirms the issue is not due to browser.

**Response for your second post:**
1. I am not sure about Jira support recommending Web app with OAuth. I'm surprised that they are even aware of such an option.
2. With the screenshot you shared, I was able to identify and fix one of the issue related to Cross Origin with Firefox. So now Cross origin issue you faced with Firefox would have been resolved now. However you may continue to face the initial error with Firefox now.
3. None of the 403 or 404 errors in the screenshot you shared looks relevant for the issue you are facing. So I don't think we need to think further about those errors.


After digging into the code, I see all the error's are handled and if should fail with appropriate message. If it is stuck at this point, then most probably something could be blocking some requests or some request is taking very long time and never gets completed.

If its not too much, will you be able to check it once again from Web version by having the network tab open and see if any requests are failing or not getting completed. If you observe anything like that, then please share the screenshot of both network tab and console once again.

Also if its possible, will you be able to try it once from outside of your current network / system to see if something in your network is blocking.

If the issue persist, please contact me via mail for other debugging options which I'm hesitant to mention in public forums like this.

**Comment by NODeeJay** [comment] 2023-10-10 18:51
Hi Shridar,

yes, I am strongly conviced the issue is not related browser, OS or even connection. Many of us work from home using home connection to connect to Internet, only internal resources are routed over the VPN, and at the time we realized the issue, some of us where on business trip in other countries or connected over cell phone network.

The web version works now without any issues, I can confirm with FF and Edge, I will uninstall, wait a bit and reinstall JA in Jira Cloud. 

Meanwhile I did investigation on FF 118.0.1 x64 on W10 22H2 Enterprise:
![image](https://github.com/shridhar-tl/jira-assistant/assets/83764033/656c9832-762e-41a4-af91-f21712873058)
![image](https://github.com/shridhar-tl/jira-assistant/assets/83764033/541dc07f-86bd-41ed-9ef6-fc0d1f350a80)

![image](https://github.com/shridhar-tl/jira-assistant/assets/83764033/c42fdd7b-504d-4b5d-84bb-485a34f4b827)
![image](https://github.com/shridhar-tl/jira-assistant/assets/83764033/0bdf0a38-02a6-4a2e-b1eb-f67fe4595abb)

Under the last 404 for the failed API call there are some more 200, nothing of real interest.

Here is another shortened recording from Edge 117.0.2045.60 (Official build) (64-bit)
![image](https://github.com/shridhar-tl/jira-assistant/assets/83764033/0ab48936-8ff9-4b0e-95c7-83fcb9c795d4)
![image](https://github.com/shridhar-tl/jira-assistant/assets/83764033/abb1571a-1d96-40d2-a3f1-b1feb15524f5)

Yes, actually Jira support recommended to try from the app the webversion. Shall I add your gmail to the Atlassian ticket?
![image](https://github.com/shridhar-tl/jira-assistant/assets/83764033/537e0e68-bd51-4764-a555-e061083ae1fb)

I have the impression there is an issue with the general authentication of the app. Even though I reinstalled it several times, the authorization was never requested again, just when I use the webapp it's requested.

Thanks for the Firefox fix!

**Comment by shridhar-tl** [comment] 2023-10-11 04:31
Hi @NODeeJay,
Thank you for the invite and yes, that is very much helpful to debug the issue. 

I have added additional logs to help me with debugging.

Here are my initial findings which can help you to go back to Atlassian. I will do further research and try out few things to see if I can do something to solve it from my end. However its better to once reach out to Atlassian to see if they were able to provide some info on why this issue is occurring.

Additionally, I have also identified one more issue with how Jira is handling OAuth authentication when there are multiple instance of Jira. But for now that is of lesser priority. Once this issue is resolved, I will reach out to Atlassian myself with details about that issue.

Here are the details for now:
As Jira Assistant uses Atlas Forge framework (As suggested by Atlassian), it uses following code to fetch profile information from Jira.

`
import { requestJira } from '@forge/bridge';
return requestJira('/rest/api/2/myself', { method:'GET' });
`

The above http request fails with the following error:
![Auth Token Error](https://github.com/shridhar-tl/jira-assistant/assets/37339683/03652650-e9d5-47e9-8bbf-84343a78a46e)

While further debugging it goes through following lines:
![JiraCloudError](https://github.com/shridhar-tl/jira-assistant/assets/37339683/cda1ac0e-3c6f-4f37-aa4d-ce344a2f8e19)

Here is the console error log of the final error:
![Console Error Log](https://github.com/shridhar-tl/jira-assistant/assets/37339683/e353e716-91a6-4cb6-9c7d-7647d82f4c1d)


This need not be necessarily an issue. But in this case, Jira should prompt the user for doing OAuth which isn't happening. I will try to use my dev version and do further testing on this and get back to you with more updates later today.

I am holding on with my other development activities and this would be my top most priority for now. If this is fixable from my end, I will see to that I get it fixed within this week.

**Comment by shridhar-tl** [comment] 2023-10-11 05:33
Hi, One more update.
Once I de-authorize my existing user in my dev environment, I was able to reproduce this issue for my environment as well.

While looking at recent updates in Jira, I came across the following change which looks more similar to what we are facing. I'm still not sure if this could be the cause. However, it appears that the issue is with Jira only and its related to Consent flow only. When it comes to Cloud Forge App (like JA), Jira  was suppose to show the consent flow when first "requestJira" call was made, but it is not showing and not automatically authenticating the user as well. So the app keeps waiting for ever for the user to be authenticated.

Reference Url: https://developer.atlassian.com/platform/forge/simplified-user-consent/

I will further debug the issue and get back to you later if I get any further updates. Hope for now you should be good with using Web version at least to unblock you from day to day usage. I will keep you posted.

**Comment by githubdarren** [comment] 2023-10-11 11:45
Hi @shridhar-tl , we have one user in our environment who's experiencing this same issue where it gets stuck at 'setting up'. This is new error we haven't seen before, not like the 'authenticating' one where a page-refresh fixes it. All other users are accessing okay. This started for this user when they logged in this morning and clearing cookies, forced log-out from jira, and restarting windows didn't work. Issue is in Microsoft Edge Version 117.0.2045.60 (Official build) (64-bit).

**Comment by shridhar-tl** [comment] 2023-10-12 03:20
Hi @NODeeJay , Please look at the message from Atlassian support team. Based on this message I see JA is now working in your instance. However this looks like a temporary fix only. So you can ask all your users to authenticate now so that JA would continue to work. Just in case if it again causes any issue, let me know and I will look into it and contact support team as needed. Thank you for reporting this issue on time and all your cooperation. I will have this ticket open for now until permeant fix is available in place.

![image](https://github.com/shridhar-tl/jira-assistant/assets/37339683/0e93c467-b742-4960-b1f5-3cac5d3e9882)

FYI: @githubdarren

**Comment by shridhar-tl** [comment] 2023-10-16 03:51
Hi @NODeeJay @githubdarren 
Atlassian has closed my support ticket considering this issue as resolved. Hence I believe I can close this ticket as well as you are able to use JA Cloud app without any issues.

Please let me know otherwise.

**Closed by shridhar-tl** 2023-10-16 03:51 UTC
Labels: bug

**Comment by githubdarren** [comment] 2023-10-16 08:21
all fixed @shridhar-tl, thank you for the support and a great product!

**Comment by NODeeJay** [comment] 2023-10-16 10:14
Hi Shridhar,

sorry for my late feedback, Since Thursday last week it is working again. Thank you for your immediate support!

Cheers,
Alex
