### ISSUE TITLE
Save date range in Worklog report

### ISSUE THREAD

**Issue by Matysh** [shridhar-tl/jira-assistant#228] opened 2022-09-04 21:43 UTC
Please add ability to save configuration on screen "Worklog report" to avoid to set the date range every page openings.

**Comment by shridhar-tl** [comment] 2022-10-02 04:17
This is duplicate of #8. How ever this is implemented and is already available in Web version. Same would be published and would be available for extension users as part of Jira Assist v2.42.

**Comment by shridhar-tl** [comment] 2022-11-12 03:34
Jira Assist v2.42 is already published and this fix is available now. Hence closing this issue.

**Closed by shridhar-tl** 2022-11-12 03:34 UTC
Labels: enhancement, in live testing
