### ISSUE TITLE
Stop working after Jira Cloud's API was updated 

### ISSUE THREAD

**Issue by sjukeshov** [shridhar-tl/jira-assistant#119] opened 2020-02-17 01:58 UTC
This extension stopped working on my side starting from last Thursday. I believe it's related to Jira Cloud's API update the did.

**Comment by MoMannn** [comment] 2020-02-17 08:06
+1

**Comment by igor-inas-toptal** [comment] 2020-02-17 08:28
+1

**Comment by sol3uk** [comment] 2020-02-17 09:11
+1
![2020-02-17 09_09_04-Window](https://user-images.githubusercontent.com/26093813/74639225-6ff38b00-5165-11ea-8c5c-f7028fa0cb2d.png)

**Comment by isratmir** [comment] 2020-02-17 09:50
+1 Same issue as for @sol3uk

**Comment by andorini** [comment] 2020-02-17 10:30
+1 I have the same issue as @sol3uk

**Comment by tinemlakar** [comment] 2020-02-17 10:38
+1

**Comment by RomanChasovitin** [comment] 2020-02-17 11:22
+1 Same issue as for @sol3uk

**Comment by anzemur** [comment] 2020-02-17 11:23
+1

**Comment by sol3uk** [comment] 2020-02-17 11:27
Seems like it was resolved a few days ago:
https://github.com/shridhar-tl/jira-assistant/issues/115#issuecomment-586611456
Duplicate of #115

**Comment by sandeep-ttn** [comment] 2020-02-17 12:10
+1

**Comment by alexanderpils** [comment] 2020-02-17 12:26
It seems like the fix doesn't work #121 
I also tried the new version with firefox and it didn't work

**Comment by isratmir** [comment] 2020-02-17 12:38
@alexanderpils Confirm. Tried v0.94 on Firefox.

![image](https://user-images.githubusercontent.com/1897701/74654505-9f7db400-51b4-11ea-8692-07560e34474f.png)

**Comment by npundra** [comment] 2020-02-18 02:03
+1

**Comment by belek** [comment] 2020-02-18 09:37
+1 not working in Chrome 
Also not able to integrate extension version 0.94 with fix #115  in Firefox.

**Comment by dreamerleolioa** [comment] 2020-02-18 10:33
+1 not working at Chrome

**Comment by shridhar-tl** [comment] 2020-02-18 18:21
v0.95 was published which should solve most of the issue. It is available in Firefox already. But Chrome takes time for review and may take upto 4 days unfortunately.

But additionally, Jira has issue with User-Agent header of Chrome v80 and Firefox browsers which cause XSRF check failed issue for POST and PUT requests. For Firefox workaround is available since long time. But for chrome it just started occurring. Basically I will have to try to remove or modify User-Agent header in request to solve this and chrome does not support doing it. So still no solution was found to solve this issue and I was stuck here.

**Comment by shridhar-tl** [comment] 2020-02-18 18:25
After your version gets updated to v0.95, sometimes you may need to remove and add the users to user groups once again for the reports to work.

I know this is annoying , but right now have lots of issues to work and its hard to find time to fix issues for which workaround is available.

**Comment by Che994** [comment] 2020-02-19 04:09
> After your version gets updated to v0.95, sometimes you may need to remove and add the users to user groups once again for the reports to work.
> 
> I know this is annoying , but right now have lots of issues to work and its hard to find time to fix issues for which workaround is available.

I have installed 0.95v and try to get the worklogs but its not loading properly .Reports are not getting generated

**Comment by MrDazt** [comment] 2020-02-19 04:10
Where we can download chrome extension manually without waiting for approving chrome review ?

**Comment by vinaychavadi** [comment] 2020-02-19 13:55
I tried with Firefox and Chrome multiple times but the 0.95 version  it is not working. Plz help!!

**Comment by MrDazt** [comment] 2020-02-20 12:51
We need to wait for 0.96 until chrome store processed it

**Comment by shridhar-tl** [comment] 2020-02-28 17:40
Hope this issue got resolved and remaining issues would be resolved by v0.97 version. Their are other open tickets related to this issue and hence closing this issue.

**Closed by shridhar-tl** 2020-02-28 17:40 UTC
