### ISSUE TITLE
New worklog report does not work at all and shows completely empty.  Please DO NOT remove the old one.

### ISSUE THREAD

**Issue by cygnus2048** [shridhar-tl/jira-assistant#283] opened 2023-02-24 17:09 UTC
### Checklist before you being

- [X] I am sure that I am already using latest version of Jira Assistant
- [X] I had verified that, no similar issues are already reported in [issue tracker](https://github.com/shridhar-tl/jira-assistant/issues)
- [X] I had tried reproducing this issue with with [Web version of Jira Assistant](https://app.jiraassistant.com) to ensure that this issue is not recently fixed and yet to be published
- [X] I had verified that, my query is not answered in [FAQ section of website](https://www.jiraassistant.com/faq)
- [X] I had verified that, my issue is not listed as [known bugs in website](https://www.jiraassistant.com/version-history)

### How do you use Jira Assistant?

Browser extension

### Are you using cloud version of Jira or self hosted (data center / server) of Jira.

Self hosted (datacenter)

### Version of Jira Assistant

2.47

### What browser are you using?

Chrome

### What OS are you using? You need not disclose this if you feel it is irr-relevant for your issue.

None

### Bug Description

The new worklog report shows up as completely empty for me, while the old one works just fine.

Can you please NOT make the new one the default or at least provide an option to use always use the old one?

Don't know why a "new" one was needed as I thought the old one worked just fine, but at least don't force it on me as it obviously has issues.

### Checklist before you submit

- [X] I have ensured not to paste any confidential information like Jira url, Mail id, etc.
- [X] I have verified my browser console logs and added necessary details (if required)
- [X] I have added required screenshots if the bug is related to UI (as necessary)

**Comment by shridhar-tl** [comment] 2023-02-25 03:30
Hi @cygnus2048 - Sorry for the inconvenience and until the new version is working as expected, old version would continue to be there and I would not remove it.

However, did you try to reproduce this issue with Web version of Jira Assistant? I believe this issue has already been resolved in Web Version. Please verify this with Web version once and let me know if it resolves your issue. If I get the confirmation that it is resolved in Web version, then I will publish the updates for extension.

Additionally this is duplicate of #253 & #254 and hence I would be closing this issue once I get your reply.

**Comment by shridhar-tl** [comment] 2023-03-06 04:30
Hi @cygnus2048 - I am closing this issue considering this issue is duplicate and is resolved. Please retest this issue with Jira Assistant v2.48 or with Web version and let me know if you still face any issue.

**Closed by shridhar-tl** 2023-03-06 04:30 UTC
Labels: bug, duplicate

**Comment by cygnus2048** [comment] 2023-03-13 16:03
I have verified with v2.48 and it does show correctly now.  I would like to point out though that I find the appearance of the "new" much less desirable than the "old" so I will continue to use the "old" and I ask that you do not remove it and please leave it an option for those of us who prefer it.  Thank you.

**Comment by shridhar-tl** [comment] 2023-03-14 04:03
Hi @cygnus2048, when you say "new" report is much less desirable than "old", what do you mean by it? Why do you prefer to use "old" report when there are lot more features added than old and what ever is available in "old" is still available in "new" report as well.

If you talking about look and feel, please look at the settings of "new" report and you can change the configuration to use same styling as that of "old" report.

I would like to let you know that there will not be any more enhancement in Old report as it is migrated from different technology earlier and hard to maintain or do customizations. That was the first reason to take time in building a new report instead of adding feature to existing one.

**Comment by cygnus2048** [comment] 2023-03-14 17:03
Yes, I do mean the look and feel.  The colored background is much easier to glance at for info compared to the new bars at the bottom.   Moreover, when expanding on a user, the new view splits each item in multiple lines, which spreads out the hours on the right hand side to double the vertical space it used to use.  Also, not only is splitting the ticket name into multiple lines (putting the hour details on line two) it is truncating the task name as well as not showing the state.  Just many things about this new which I don't care for at all.

**Comment by shridhar-tl** [comment] 2023-03-17 05:41
Thank you @cygnus2048 for your response. Here are my comments for your issues:

**The colored background is much easier to glance at for info compared to the new bars at the bottom.**
**A)** Background color is not gone, you can still change it from configurations as I mentioned earlier. Open configurations and go to Formatting tab, expand more options and you will see the following settings which lets you get the old background highlighting back:
![image](https://user-images.githubusercontent.com/37339683/225818858-1c140395-b3df-4f40-ac3d-7f2415b4df75.png)

**Moreover, when expanding on a user, the new view splits each item in multiple lines, which spreads out the hours on the right hand side to double the vertical space it used to use.**
**A)** This is not true. In fact, **New report is more compact** and uses less vertical space. May be you are using different log hour format for both the report. Change the log hour format configuration from Report configurations, Formatting tab and you should see new report consume lesser space than old report.

**New report (Looks better and more compact for same set of data):**
![image](https://user-images.githubusercontent.com/37339683/225819731-a2a24691-2628-4a9b-9f44-7a7ca6e938a9.png)

Old report (Uses lot more space)
![image](https://user-images.githubusercontent.com/37339683/225819920-a747a2c3-797f-4bbb-9818-4e2605dcc6d1.png)

**Also, not only is splitting the ticket name into multiple lines**
**A)** What do you mean by splitting the ticket name. What do you refer as ticket name? What ever it is, I don't think anything is splitted to multiple lines

**(putting the hour details on line two)**
**A)** As mentioned above, you may be using different hour format in both the reports. If you use same formatting, New report would still look more compact.

**it is truncating the task name as well**
A) Are you referring to "issue summary" by any chance? I hope issue summary are just an indicator to understand what issue users had logged work on. I don't really see any need to display display the whole summary and span the report to double in height. And this is not my individual decision, but based on lots of feedback received from users over years.

Any way, if you want to look at whole summary for some cases, just hovering over the summary displays the complete text as tooltip. Any way, if you feel it is necessary, let this not be a problem, I will add an additional settings in upcoming release to show whole summary like in old report.

**not showing the state**
This is already a setting for you to configure. Just enable "Show status" checkbox from Fields list tab under Report Configurations and you should see it.

Almost all these changes are not just based on my preference and is based on user feedback and minimal UX consultations as well. And none of the features are lots in new report. Everything is behind configuration only and you can customize it the way you need it.

**Comment by cygnus2048** [comment] 2023-03-17 14:21
I appreciate the detailed response.  I was able to configure the background colors, so thank you for that.
Regarding the truncation and multiple lines.  It is hard to describe so I will try to show the difference...
![image](https://user-images.githubusercontent.com/35502570/225931262-4d79c426-25fb-4346-a2b1-eb033f11eb4d.png)
![image](https://user-images.githubusercontent.com/35502570/225931471-28920e38-3fb7-4a60-9cbb-0aacd0fa7890.png)
Notice a nice single line in the old, but the new is truncated as well as the hours put on the second line.

**Comment by shridhar-tl** [comment] 2023-03-18 03:15
Ok @cygnus2048 I get it now. Thank you for the screenshot. Will fix this as well in upcoming release. And if there are any other issues / suggestions, please feel free to let me know and I will address it ASAP.

And as I told earlier, until all the issues are resolved and everyone is comfortable using the new report, old report would remain. So you need not worry about old report getting removed.

**Comment by cygnus2048** [comment] 2023-04-01 06:09
I found one other minor annoyance with the new report.  When I click on refresh it collapses all the users I had expanded.  The old report maintains this and does not collapse them.

**Comment by shridhar-tl** [comment] 2023-05-03 02:59
Hi @cygnus2048 - Both the issues you mentioned above is resolved and is already available in Web version of Jira Assistant. This would be published to extension as part of JA v2.49 in next couple of weeks max. Until then if you would like to try it to see if it works as expected, you can try it out in Web version by accessing https://app.jiraassistant.com
