### ISSUE TITLE
Delete Reports cause to Unhandled error

### ISSUE THREAD

**Issue by kxMaxx** [shridhar-tl/jira-assistant#280] opened 2023-02-13 15:17 UTC
### Checklist before you being

- [X] I am sure that I am already using latest version of Jira Assistant
- [X] I had verified that, no similar issues are already reported in [issue tracker](https://github.com/shridhar-tl/jira-assistant/issues)
- [X] I had tried reproducing this issue with with [Web version of Jira Assistant](https://app.jiraassistant.com) to ensure that this issue is not recently fixed and yet to be published
- [X] I had verified that, my query is not answered in [FAQ section of website](https://www.jiraassistant.com/faq)
- [X] I had verified that, my issue is not listed as [known bugs in website](https://www.jiraassistant.com/version-history)

### How do you use Jira Assistant?

Browser extension

### Are you using cloud version of Jira or self hosted (data center / server) of Jira.

Self hosted (datacenter)

### Version of Jira Assistant

2.47

### What browser are you using?

Firefox

### What OS are you using? You need not disclose this if you feel it is irr-relevant for your issue.

Windows

### Bug Description

Use Report Builder an create an report.
Deleting the report again is impossible.

The "Delete Query" button is confirmed with a message:
Unhandled error.
An unknown error occurred while processing your request.

The report still exists.

Another bug: If there is such a customized report, it is not possible to export the settings via "Export Settings including Reports". This leads to the same error.

### Checklist before you submit

- [X] I have ensured not to paste any confidential information like Jira url, Mail id, etc.
- [X] I have verified my browser console logs and added necessary details (if required)
- [X] I have added required screenshots if the bug is related to UI (as necessary)

**Comment by shridhar-tl** [comment] 2023-02-14 03:45
Hi @kxMaxx - The issue you mentioned about deleting a report has broken couple of months back due to a major refactoring. Now that is resolved and would be part of next release. For now it is already available in Web version and you can use it to delete the report if you wanted to do it right away. You can access the web version by visiting https://app.jiraassistant.com and connecting with your extension.

However, I was not able to reproduce the issue you mentioned about exporting settings fails while we include reports as well. I tried to export the settings including reports and it did work without issues. Can you retry that and send me a screenshot of the console error so that I will see if error details helps me to identify the issue.

**Comment by kxMaxx** [comment] 2023-02-14 07:28
Here some outputs:
[DeleteQuery1.Log](https://github.com/shridhar-tl/jira-assistant/files/10729801/DeleteQuery1.Log)
[ExportAllSettings.Log](https://github.com/shridhar-tl/jira-assistant/files/10729800/ExportAllSettings.Log)

**Comment by shridhar-tl** [comment] 2023-02-18 05:03
Hi @kxMaxx - This issue has been resolved in JA v2.48 and would be available for extension users by end of this month. However it is immediately available for Web version of Jira Assistant. You can try this functionality once in Web version to see if your issue is resolved.

[Background]
After trying a lots of scenario's, finally identified that export is failing due to usage of columns which has non Latin chars in field names. Following screenshot shows example of such fields from Jira. Inbuild encode function does not support this and hence had done custom implementation for the same.

![image](https://user-images.githubusercontent.com/37339683/219838720-0624961c-0f7a-43ef-89a4-5f418b5673ad.png)

I'm closing this issue considering this issue is resolved. After trying in web version, if you still face any issue, please feel free to reopen this ticket.

**Closed by shridhar-tl** 2023-02-18 05:03 UTC
Labels: bug
