### ISSUE TITLE
Blank page is coming if we refresh the New worklog report page

### ISSUE THREAD

**Issue by SelvalakshmiPraveen** [shridhar-tl/jira-assistant#311] opened 2023-07-25 08:38 UTC
### Checklist before you being

- [X] I am sure that I am already using latest version of Jira Assistant
- [X] I had verified that, no similar issues are already reported in [issue tracker](https://github.com/shridhar-tl/jira-assistant/issues)
- [X] I had tried reproducing this issue with with [Web version of Jira Assistant](https://app.jiraassistant.com) to ensure that this issue is not recently fixed and yet to be published
- [X] I had verified that, my query is not answered in [FAQ section of website](https://www.jiraassistant.com/faq)
- [X] I had verified that, my issue is not listed as [known bugs in website](https://www.jiraassistant.com/version-history)

### How do you use Jira Assistant?

Browser extension

### Are you using cloud version of Jira or self hosted (data center / server) of Jira.

Cloud Jira

### Version of Jira Assistant

Web

### What browser are you using?

Chrome

### What OS are you using? You need not disclose this if you feel it is irr-relevant for your issue.

None

### Bug Description

Blank page is coming if we refresh the New worklog report page

<img width="960" alt="image" src="https://github.com/shridhar-tl/jira-assistant/assets/78785914/fc4f529a-7996-4eb2-ab92-61853bfac8fa">

<img width="960" alt="image" src="https://github.com/shridhar-tl/jira-assistant/assets/78785914/1f189bd4-6b9d-4604-a4de-f2a2b9a1bbb1">

### Checklist before you submit

- [X] I have ensured not to paste any confidential information like Jira url, Mail id, etc.
- [X] I have verified my browser console logs and added necessary details (if required)
- [X] I have added required screenshots if the bug is related to UI (as necessary)

**Comment by shridhar-tl** [comment] 2023-07-26 03:23
Hi @SelvalakshmiPraveen 
Thank you for reporting this issue. However, I was not able to reproduce it in my end.

Can you please send the screenshot of console error log also so that it would give me a clue of what is causing this issue. Also let me know if you are using sprint wise report or date range wise (default) report.

**Comment by SelvalakshmiPraveen** [comment] 2023-07-26 05:15
Hi @shridhar-tl ,

Thanks for your reply. I am using the date range wise report (default). Please find below the Console log error message. I have also attached the screenshot for your reference.

index.7c232e8e.js:2 TypeError: (intermediate value)(intermediate value)(intermediate value) is not iterable
    at 211.78f6f8df.chunk.js:1:152111
    at Object.useMemo (index.7c232e8e.js:2:2274064)
    at t.useMemo (index.7c232e8e.js:2:2357961)
    at 211.78f6f8df.chunk.js:1:152089
    at ya (index.7c232e8e.js:2:2267696)
    at yc (index.7c232e8e.js:2:2324809)
    at mp (index.7c232e8e.js:2:2313915)
    at hp (index.7c232e8e.js:2:2313843)
    at fp (index.7c232e8e.js:2:2313706)
    at ap (index.7c232e8e.js:2:2310486)
bs @ index.7c232e8e.js:2
n.callback @ index.7c232e8e.js:2
_i @ index.7c232e8e.js:2
gc @ index.7c232e8e.js:2
mc @ index.7c232e8e.js:2
Ac @ index.7c232e8e.js:2
(anonymous) @ index.7c232e8e.js:2
qp @ index.7c232e8e.js:2
ip @ index.7c232e8e.js:2
q @ index.7c232e8e.js:2
E @ index.7c232e8e.js:2
index.7c232e8e.js:2 Global handler:- ErrorEvent {isTrusted: true, message: 'Uncaught TypeError: (intermediate value)(intermediate value)(intermediate value) is not iterable', filename: 'chrome-extension://momjbjbjpbcbnepbgkkiaofkgimihbii/static/js/index.7c232e8e.js', lineno: 2, colno: 2317189, …}
(anonymous) @ index.7c232e8e.js:2
index.7c232e8e.js:2 Uncaught TypeError: (intermediate value)(intermediate value)(intermediate value) is not iterable
    at 211.78f6f8df.chunk.js:1:152111
    at Object.useMemo (index.7c232e8e.js:2:2274064)
    at t.useMemo (index.7c232e8e.js:2:2357961)
    at 211.78f6f8df.chunk.js:1:152089
    at ya (index.7c232e8e.js:2:2267696)
    at yc (index.7c232e8e.js:2:2324809)
    at mp (index.7c232e8e.js:2:2313915)
    at hp (index.7c232e8e.js:2:2313843)
    at fp (index.7c232e8e.js:2:2313706)
    at ap (index.7c232e8e.js:2:2310486)
(anonymous) @ 211.78f6f8df.chunk.js:1
useMemo @ index.7c232e8e.js:2
t.useMemo @ index.7c232e8e.js:2
(anonymous) @ 211.78f6f8df.chunk.js:1
ya @ index.7c232e8e.js:2
yc @ index.7c232e8e.js:2
mp @ index.7c232e8e.js:2
hp @ index.7c232e8e.js:2
fp @ index.7c232e8e.js:2
ap @ index.7c232e8e.js:2
ip @ index.7c232e8e.js:2
q @ index.7c232e8e.js:2
E @ index.7c232e8e.js:2
background.js:2 Received request from  {sender: {…}, message: {…}}
background.js:2 Received request from  {sender: {…}, message: {…}}
background.js:2 Received request from  {sender: {…}, message: {…}}
index.7c232e8e.js:2 Keeping SW alive Wed Jul 26 2023 10:41:37 GMT+0530 (India Standard Time)
index.html#/2/reports/worklog:1 Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.


<img width="960" alt="image" src="https://github.com/shridhar-tl/jira-assistant/assets/78785914/ebb18106-344a-4288-874e-3a2cc7245975">

**Comment by shridhar-tl** [comment] 2023-07-27 03:28
Hi @SelvalakshmiPraveen,
You mentioned you are using web version of Jira, however looking at screenshot I realize you are using chrome extension.

Can you let me know what version of extension you are using? As far as I know this bug is already resolved in latest version of chrome extension. If you are using old version of extension, please update your extension to JA v2.52 and this issue should get resolved.

To update your extension please go to chrome://extension and turn on dev mode from top right corner and then click update button from top left corner. This should most probably solve this issue. If you were still not able to resolve this issue, try visiting https://app.jiraassistant.com/?authType=1 and see if you were able to reproduce this issue and let me know.

Apologies for the inconvenience caused, however as I was not able to reproduce the issue in my end, I need more help from you to identify the root cause of this issue.

**Comment by SelvalakshmiPraveen** [comment] 2023-07-27 05:05
Hi,

Thanks for your great support. After I have updated my chrome extension, I
am able to view the New worklog report Page.

We are good to close this ticket now.





Warm Regards,
Selvalakshmi Praveen Kumar

**Closed** 2023-07-27 05:32 UTC
Labels: bug, unable to reproduce
